### ISSUE TITLE
[BUG] QuickAdd to daily note creates file with raw date format instead creating/appending to today's note

### ISSUE THREAD

**Issue by tomireland** [chhoumann/quickadd#107]
**Description**
When using QuickAdd to add a note to my daily note, instead of the text added to the note (if it exists) or creation of a new file with the correct filename format (if it doesn't exist), a file is created with the filename `{{YYYY-MM-DD, ddd}}`.

I followed the instructions in the [Capture](https://github.com/chhoumann/quickadd/blob/master/docs/Choices/CaptureChoice.md) documentation.

**Created note**
![created-note](https://user-images.githubusercontent.com/1268067/134315479-1f725e7f-be17-4f93-b729-36c373a00a9d.png)

**QuickAdd settings 1**
![quickadd-settings-1](https://user-images.githubusercontent.com/1268067/134315530-ae3ad1b4-9170-447f-b434-d4acbdb6907b.png)

**QuickAdd settings 2**
![quickadd-settings-2](https://user-images.githubusercontent.com/1268067/134315560-0500ee6c-4987-420f-917a-d0d03c64fe17.png)

Note that my daily note plugin date format was used as the basis for the filename in the QuickAdd capture settings and the output in the QuickAdd capture settings seems to parse the date okay.

**To Reproduce**
1. Set up the QuickAdd capture settings as per the 'quickadd-settings-*' images above.
2. Execute hotkey for the QuickAdd capture.
3. Add your note.
4. Confirm a file is created with the filename `{{YYYY-MM-DD, ddd}}` and your note is present in the file (not expected). 

**Expected behavior**
A new file should be created with the appropriate filename e.g. `2021-09-22, Wed` and the note added (if the file does not exist) or the note added to an existing note with the same filename.

**Desktop**
 - OS: Ubuntu 20.04
 - Browser: Firefox 92.0

**Obsidian**
Version: 0.12.15
QuickAdd version: 0.4.6

**Comment by tomireland** [comment]
I just found out how to work around the problem. It seems you have to disable and then re-enable the command/hotkey in the QuickAdd settings. Initially, I had copied and pasted the date format but it had not parsed correctly, however, I had re-entered the format _after_ enabling the command. I only came across this because I decided to test changing the format from `{{YYYY-MM-DD, ddd}} to `YYYY-MM-DD` thinking it was an issue with the comma or `ddd`. When using the command, it was still creating a file with the filename `{{YYYY-MM-DD, ddd}}, so I disabled the command and re-enabled it, then "hey presto!", it worked. I then changed the format to what I wanted, disabled and re-enabled the command, and it now works as expected.

I cannot see any reference to disabling and re-enabling the hotkey in the documentation, so I'll update the steps as I still think that's a bug.

**Comment by chhoumann** [comment]
Hi @tomireland 

Thank you very much for reporting this. I'm glad to see that you found a fix before I could answer.

What you mention was indeed a bug. It was fixed in a recent update, so everything should be working.

Best, Christian
