### ISSUE TITLE
[BUG] More info to debug "Could not create file with template. Maybe '${templatePath}' is an invalid template path? received for valid template path"

### ISSUE THREAD

**Issue by claremacrae** [chhoumann/quickadd#111]
**Describe the bug**
It would be helpful to have more information in the error message:

```
Could not create file with template. Maybe '${templatePath}' is an invalid template path?
```

**What I'm doing**

Following your video: https://youtu.be/gYK3VDQsZJo?t=788

**Background**

I'm getting this message for a file that definitely exists:

![image](https://user-images.githubusercontent.com/4840096/134959409-e4dbbf33-ac5c-4aca-8d8e-507e2cc76b34.png)

My file template definitely exists, and Templater is definitely running - so I'm struggling to know what to do next.

I see in the code that there is an exception object:

```typescript
        catch (e) {
            log.logError(`Could not create file with template. Maybe '${templatePath}' is an invalid template path?`);
            return null;
        }
```

Is there any possibility that the text of the exception could be included in the error message please?

**Comment by Borber** [comment]
It should also be caused by the templater upgrade

**Comment by claremacrae** [comment]
It's looking like this might be caused by a change in Templater - but I can now log here my setup:

## 1 Templater template

File name: `_templates/NewFileTemplate.md`

And content:

```markdown
# <% tp.file.title %>

```

## 2 Templater settings:

```json
{
  "command_timeout": 5,
  "templates_folder": "_templates",
  "templates_pairs": [
    [
      "",
      ""
    ]
  ],
  "trigger_on_file_creation": false,
  "enable_system_commands": false,
  "shell_path": "",
  "user_scripts_folder": "_meta/_scripts",
  "empty_file_template": "",
  "syntax_highlighting": true,
  "enabled_templates_hotkeys": [
    ""
  ],
  "startup_templates": [
    ""
  ]
}
```

![image](https://user-images.githubusercontent.com/4840096/134957102-09a93b83-1029-43a4-86b2-8f154096cfff.png)

![image](https://user-images.githubusercontent.com/4840096/134957154-33cca5bd-9833-40de-8de1-8cc5a04bd581.png)

# 3 quickadd settings

```json
{
  "choices": [
    {
      "id": "648a2dbc-1fd0-4642-982b-8845d07e7449",
      "name": "New File",
      "type": "Template",
      "command": false,
      "templatePath": "_templates/NewFileTemplate.md",
      "fileNameFormat": {
        "enabled": true,
        "format": "{{VALUE}}"
      },
      "folder": {
        "enabled": true,
        "folders": [],
        "chooseWhenCreatingNote": false,
        "createInSameFolderAsActiveFile": true
      },
      "appendLink": false,
      "incrementFileName": false,
      "openFileInNewTab": {
        "enabled": true,
        "direction": "vertical",
        "focus": false
      },
      "openFile": true,
      "openFileInMode": "default"
    }
  ],
  "macros": []
}
```

![image](https://user-images.githubusercontent.com/4840096/134957270-66fbf8d6-f055-4b07-8a33-7d94ff102e3c.png)

# quickadd New File action


![image](https://user-images.githubusercontent.com/4840096/134957349-e7fd263f-915f-42bc-86c7-dba79f4c161a.png)

**Comment by claremacrae** [comment]
And the console output is:

![image](https://user-images.githubusercontent.com/4840096/134957825-d468512b-f0b9-4d2c-8b70-c30e95490342.png)

**Comment by claremacrae** [comment]
The file is created, and its contents is:

```markdown
# <% tp.file.title %>

```

In other words, the template is not expanded.

When I run the template on its own, the template is successfully expanded OK:

```
# Hello

```

**Comment by claremacrae** [comment]
Some in the Templater thread on Obsidian Discord reported:

> hello, after updating templater to 1.9.2 the option "insert template" no longer works. it just pastes the templater JS code into the file. nothing more :/

So it may be a templater problem??

**Comment by chhoumann** [comment]
Thank you for the details! I'll look into it. I believe that, because of the Templater update, the connection is now 'bugged'.

**Comment by claremacrae** [comment]
> Thank you for the details! I'll look into it. I believe that, because of the Templater update, the connection is now 'bugged'.

Thank you!

Seems I was a little unlucky picking today to start learning about quickadd and templater - but it's fine, there's plenty of other Obsidian stuff to be discovering!

**Comment by chhoumann** [comment]
Hey! I've found what seems to be a fix (after lots of testing). Can you confirm? :)

**Comment by claremacrae** [comment]
> Hey! I've found what seems to be a fix (after lots of testing). Can you confirm? :)

🎉🎉🎉🎉🎉🎉
 
Hooray - thank you very much indeed!

quickadd "0.4.8" and templater "1.9.2" work fine for creating new files.

I'll pop a message in the Obsidian Discord templater thread, where someone else was asking about what may be the same problem.

**Comment by GitMurf** [comment]
> Hey! I've found what seems to be a fix (after lots of testing). Can you confirm? :)

Could you provide a little insight into what the issue was? as people are telling me many of my templater scripts are not working for them all the sudden and I suspect for the same reasons as quick add had issues. Thanks!

**Comment by GitMurf** [comment]
Also will the newest version of QuickAdd still work with the previous version of templater? I am using previous version because of issues in the update. I don’t want to update QuickAdd either if it requires the newest version of templater. Thanks!

**Comment by claremacrae** [comment]
I’m very grateful to @chhoumann for working  round the change caused by temp later, but I think that is probably time for this conversation to move to the templater github repo  -  It doesn’t seem too fair to me for the author of this plug-in to accidentally end up doing kind of user support for the templater plug-in users…

**Comment by claremacrae** [comment]
Having said that, I put this on the Templater thread in Obsidian Discord earlier:

> If any other plugin authors are having the same problem, the relevant code change was in `src/utility.ts` in this diff: <https://github.com/chhoumann/quickadd/compare/0.4.6...0.4.8>

**Comment by claremacrae** [comment]
@GitMurf see previous message…

**Comment by chhoumann** [comment]
Thank you very much, @claremacrae. I'm glad it works!

@GitMurf In this case, it was just a bad function call that I was hooking to - as seen in https://github.com/chhoumann/quickadd/issues/111#issuecomment-928953216 :)

**Comment by flatrick** [comment]
Hi, sorry for commenting on a closed ticket, but this particular error-message also appears when using non-legal characters as a title/filename, such as a questionmark (?) on Windows-machines.

Would you rather see a separate ticket for this?

**Comment by chhoumann** [comment]
> Hi, sorry for commenting on a closed ticket, but this particular error-message also appears when using non-legal characters as a title/filename, such as a questionmark (?) on Windows-machines.
> 
> 
> 
> Would you rather see a separate ticket for this?

It's all right. If an illegal character is given, then it can't create the file - so it's working as intended. Or am I missing something?

**Comment by flatrick** [comment]
> > Hi, sorry for commenting on a closed ticket, but this particular error-message also appears when using non-legal characters as a title/filename, such as a questionmark (?) on Windows-machines.
> > Would you rather see a separate ticket for this?
> 
> It's all right. If an illegal character is given, then it can't create the file - so it's working as intended. Or am I missing something?

In a sense, yes. But the problem is that the error-message is misleading as it points to an error with the template instead of the filename of the new note.

**Comment by Lulullia** [comment]
> In a sense, yes. But the problem is that the error-message is misleading as it points to an error with the template instead of the filename of the new note.

Yes, I just lost 20m trying to understand why it wouldn't capture when it worked fine just a while ago. It was because I captured something with the character `"`
Now I know but it can still happen to others, and it should be a quick fix hopefully, please make this a priority

And as always thanks for this incredible plugin!
