### ISSUE TITLE
[FEATURE REQUEST] Capture Multi-line input

### ISSUE THREAD

**Issue by Borber** [chhoumann/quickadd#114]
Similar to this https://twitter.com/TfTHacker/status/1439178293618618371

![image](https://user-images.githubusercontent.com/30563826/135015744-baead8ee-4cf2-4274-a05d-f471cea49459.png)

**Comment by alexlyzhov** [comment]
Came here to create this issue - half of the things I capture to my daily notes are multiline, so this seems essential for my use-case

**Comment by alexlyzhov** [comment]
I noticed you can use `\n` to create new lines but this doesn't automatically work if you copy and paste from an external source.

**Comment by chhoumann** [comment]
Thanks guys! This has been added in v0.4.18

**Comment by rushikb** [comment]
Is there a way to make this configurable at a more granular level? I love multi line input but at present the only option is to have this apply to ALL macros or none of them .
