### ISSUE TITLE
[BUG] TypeError: Assignment to constant variable

### ISSUE THREAD

**Issue by link-ding** [chhoumann/quickadd#116]
**Describe the bug**
I write a quickadd which can add a line to daily note but it does not work and I find a error message in the console.
![image](https://user-images.githubusercontent.com/49264539/135395824-449c7c78-1ef0-4ff4-ac89-3d02f7848dd1.png)

**To Reproduce**
1. run the quickadd
2. nothing happen
3. check the console

**Desktop (please complete the following information):**
 - OS: macos
 - latest version

**Comment by chhoumann** [comment]
Hey @link-ding. This seemed to be a Templater issue. I believe it has been fixed:
- https://github.com/SilentVoid13/Templater/issues/392
- https://github.com/SilentVoid13/Templater/issues/391
