### ISSUE TITLE
[BUG] Dates in Filename not parsed

### ISSUE THREAD

**Issue by curtismchale** [chhoumann/quickadd#127]
**Describe the bug**
Using Capture To I'm trying to log the current file to my Daily Note. My date format does show up properly in settings for QuickAdd but it doesn't actually parse into a date. Instead it shows up in my Daily notes as {{YYYY-MM-DD}} and the note I'm trying to log does not get logged into the file either.

Console error:
```
QuickAdd: (LOG) TemplaterError: Invalid reference date format, try specifying one with the argument 'reference_format' VM133:15096
```
Setup of Capture To:
<img width="926" alt="Screen Shot 2021-10-13 at 7 11 09 AM" src="https://user-images.githubusercontent.com/74561/137150054-0472d219-cfa5-4db6-b32e-08aa98138c19.png">

<img width="895" alt="Screen Shot 2021-10-13 at 7 12 41 AM" src="https://user-images.githubusercontent.com/74561/137150372-f4bf3f02-4818-47db-a1f6-6d917e4978f0.png">

**To Reproduce**
1. Setup Quick Add as described
2. Run Action
3. See file created but not with proper date format and not with link to the file I was currently active in

**Expected behavior**
I expect that Quick Add will create the file if it doesn't exist and then log the link to the current file after the Reading heading.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS, iPadOS 15

**Smartphone (please complete the following information):**
 - Device: M1 iPad Pro
 - OS: 15.0.1
 - Browser Stock Safari
 - Version latest

**Additional context**
Templater also shows an error at the same time, but that may be because it's looking at the file name to get the date it wants to parse into the variables and {{YYYY-MM-DD}} isn't a valid date.

<img width="334" alt="Screen Shot 2021-10-13 at 7 01 48 AM" src="https://user-images.githubusercontent.com/74561/137150840-75664861-2523-4f46-ad47-7027887316fb.png">

Possibly Related:

https://github.com/chhoumann/quickadd/issues/119

**Comment by Borber** [comment]
Can i take a look at your template, I feel that your template may be the cause of the problem
