### ISSUE TITLE
[FEATURE REQUEST] insert a H3 at end of H2 section

### ISSUE THREAD

**Issue by Awyugan** [chhoumann/quickadd#134]
The plug-in is so great, but I have a puzzle at present. When inserting 'insert at end of section', I can't insert a `## heading 3 `at the bottom of the `## heading 2`.

**Comment by tauren** [comment]
This would be a very good enhancement! For example, my file contains this:

```
# Meeting Notes

## Topic A

## Topic B
```

I want to insert `## Topic C` after `## Topic B`. 
But it gets inserted before `##Topic A`. 

Note that the only section header that I know the name of when configuring QuickAdd is `Meeting Notes`. The other section headers are always different.

I've tried to find a workaround, but not found one yet.
