### ISSUE TITLE
[BUG] Capture QuickAdd with "Add Command" doesn't respect the "Open" setting

### ISSUE THREAD

**Issue by timkelty** [chhoumann/quickadd#136]
**Describe the bug**
A capture that has been added as a command, does not respect the "Open" setting.
If you trigger the capture via "Run QuickAdd", it works as expected.

**To Reproduce**
1. Create a capture with "Open" toggled on
2. Enable "Add command" lightning bolt
3. Trigger command via `QuickAdd: [the name of your capture]`
4. File is written to, but not opened.
5. Trigger command via `QuickAdd: Run QuickAdd`
6. File is opened as expected

**Screenshots**
<img width="629" alt="CleanShot 2021-11-04 at 17 05 48@2x" src="https://user-images.githubusercontent.com/18329/140420001-1752192d-8a7f-41d7-b27e-a59868d8c99b.png">
<img width="513" alt="CleanShot 2021-11-04 at 17 06 07@2x" src="https://user-images.githubusercontent.com/18329/140420035-45cfe0d7-5c2a-48c0-82bb-49f827fa6546.png">

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur

**Comment by chhoumann** [comment]
Hey! Thanks for reporting this.

Does it work if you restart Obsidian?

**Comment by timkelty** [comment]
It does! 👯
