### ISSUE TITLE
[Question] Could you explain more about Template?

### ISSUE THREAD

**Issue by Quorafind** [chhoumann/quickadd#14]
Sorry that I don't know what is the best practice of using template, could you share some specific examples that make it  stronger than Templater or even Obsidian's template?

**Comment by chhoumann** [comment]
Hey! The template choice type is not meant to be a replacement for Templater or core Templates. It's meant to augment them. You can use both QuickAdd format syntax in a Templater template - and both will work.
That's one thing. But there's also all the other options: dynamic template names, adding to folders, appending links, incrementing file names, opening the file when it's created (or not), etc.

This is my book notes template. It uses both Templater and QuickAdd. I use Templater for lots of things, but I also use QuickAdd to create the file and to use the Readwise macro.

```md
---
image: 
tags: in/books
aliases:
  - <% tp.file.title.replace('{ ', '') %>
cssclass: 
---

# Title: [[<%tp.file.title%>]]

## Metadata

Tags:: <% tp.file.cursor(6) %>
Type:: [[{]]
Author:: <% tp.file.cursor(2) %>
Reference:: <% tp.file.cursor(3) %>
Rating:: <% tp.file.cursor(4) %>
Reviewed Date:: [[<%tp.date.now("gggg-MM-DD - ddd MMM D")%>]]
Finished Year:: <% tp.file.cursor(5) %>
<% tp.file.cursor(7) %>
# Thoughts

# Actions Taken / Changes

# Summary of Key Points

# Highlights & Notes
{{MACRO:Readwise}}
```

Hope this helps!

**Comment by aviskase** [comment]
@chhoumann hi, just to clarify, prompts after inputting a file name were caused by macro?
So, `{{MACRO:Readwise}}` in the template file is executed before file opening?
Before this example I was under impression that formats are used only in the quickadd settings like file name or capture, but this is even cooler.

**Comment by chhoumann** [comment]
@aviskase Yes, exactly. There's an API provided by QuickAdd which lets you use different types of prompts in your user scripts.

As you see, the format syntax can be used in templates - they're parsed before being used to create files.
