### ISSUE TITLE
[Question] Could you explain more about script?

### ISSUE THREAD

**Issue by zhl111** [chhoumann/quickadd#15]
I can't reproduce it successfully, do I need to set up metaedit? No programming knowledge, need more detailed steps, thanks a lot![image](https://user-images.githubusercontent.com/29135984/122668351-2cda7980-d1ea-11eb-83a0-b0bd65ee044c.png)

**Comment by chhoumann** [comment]
Hey! For that script to work, you need MetaEdit installed. It's in the Community Plugin store.

1. Create a Javascript file with the script in it in your vault
2. Add a new macro in the Macro Manager
3. Select the Javascript file you created as the user script
4. Add the macro to a macro choice

Like this (this example is for another script)
![FHlfsh54CF](https://user-images.githubusercontent.com/29108628/122675480-e9780f00-d1d9-11eb-8081-4c22fc8231f6.gif)

You can see the ``await Update('Book', val, \`bins/daily/${date}.md\`)` function on the second last line.
That updates the value of the book property to the value entered in the prompt. And `bins/daily/${date}.md` is the path to my daily journal note for that day.

Hope this helps!

**Comment by zhl111** [comment]
You are so sweet, the previous steps were fine but it still didn't work. Is it because of the notes path? Or am I missing some step? I am copying your script example as is.
![image](https://user-images.githubusercontent.com/29135984/122680030-f91a4680-d21f-11eb-844a-726c36e747f1.png)

**Comment by chhoumann** [comment]
It could very well be the note path, yes! My daily journals are located in my bins/daily folder, and they're named in a special way. So if yours on't have that path, it'll fail.

There's the format(...) in the script code - that's where I put the format that I use for the name of my daily notes. You could just replace that with yours.

And replace the bins/daily with the folder wherein you have your daily note files. You'll also need a property (YAML or Dataview) that is called "Book".

**Comment by zhl111** [comment]
Thank you so much!👍👍👍

**Comment by doney88** [comment]
can I retrieve content from different notes (maybe the contents after specific header), and compose all the source into one content and insert after active note? 
i guess it must be done by script , right ?

**Comment by asterialunanyx** [comment]
What do I name the file

**Comment by kongyuan** [comment]
This part of the UI is confusing and should be completely redone
