### ISSUE TITLE
"{{DATE:gggg}}.md" returns 2022 for the year as of December 27, 2021.

### ISSUE THREAD

**Issue by cansar** [chhoumann/quickadd#158]
To reproduce:
Create a Capture workflow and use "{{DATE:gggg}}.md" for the filename. The preview shows 2022, and it will show that in practice to. 

My computer clock is correct and the same thing happens on mobile. I'm thinking it may be related to the fact that the New Year starts in the middle of the week?

<img width="671" alt="image" src="https://user-images.githubusercontent.com/92989/147510215-133271c4-5d38-4765-ab6d-12c1c9621107.png">

**Comment by cansar** [comment]
My bad, I had this copy pasted from a recipe and it's correct behavior for gggg and should be yyyy instead.

**Comment by l-t-k** [comment]
I have the exact same issue at the moment, returns 2025 for the year as of December 29, 2024
