### ISSUE TITLE
[Question] Didn't work when I set a macro?

### ISSUE THREAD

**Issue by Quorafind** [chhoumann/quickadd#16]
When I wanted to add a macro , it didn't work correctly but the console has no error messages too.

I created a macro named hcow by pressing this button:

![image](https://user-images.githubusercontent.com/13215013/122669086-3a91fe00-d1ee-11eb-826a-0971657ebfc1.png)

And created a macro? by pressing this button:

![image](https://user-images.githubusercontent.com/13215013/122669098-4bdb0a80-d1ee-11eb-9619-8b9f284bfbfb.png)

![image](https://user-images.githubusercontent.com/13215013/122669104-55647280-d1ee-11eb-8e9e-bcfab21d4bfa.png)

![image](https://user-images.githubusercontent.com/13215013/122669137-7fb63000-d1ee-11eb-9c16-eca0c4c58d20.png)

Then, I made the `hcow` macro select the `Ton` macro

![image](https://user-images.githubusercontent.com/13215013/122669067-251cd400-d1ee-11eb-9fa6-869ff96ebd38.png)

Finally, I run this `hcow` macro, and it didn't do anything. Did I do something wrong?

**Comment by chhoumann** [comment]
Thank you for your report! I've fixed this in 0.1.14 :)
Used the wrong ID to execute Obsidian commands.
