### ISSUE TITLE
[FEATURE REQUEST] allow text entry modal to expand when writing longer sentences

### ISSUE THREAD

**Issue by rushikb** [chhoumann/quickadd#161]
**Is your feature request related to a problem? Please describe.**
Quickadd is one of my most used plugins — I'm not being hyperbolic when I say that it really has changed my life. I use it for therapy notes/ intermittent journalling— but one slightly annoying thing about the way that the modals for the plugin are currently rendered is that the text entry field doesn't expand when writing longer sentences. I.e. it is currently not possible to automatically wrap the sentence being written. 

**Describe the solution you'd like**
So Instead of typing a lot of test into a line, i'd want the modal to automatically wrap the text and grow in height— like with todoist.

**Additional context**
![CleanShot_2021-12-07_at_09 07 34](https://user-images.githubusercontent.com/6484525/148711571-9a300e9a-867a-4927-bdf7-dca025f9e2d3.gif)
![image](https://user-images.githubusercontent.com/6484525/148711585-ceae68c9-544b-417d-84f6-7ba3849c011b.png)

**Comment by chhoumann** [comment]
I'm super glad to hear that you find QuickAdd useful!
This feature has been implemented in the latest update :)
