### ISSUE TITLE
[FEATURE REQUEST] [UX] In QuickAdd API's yesNoPrompt : select "Yes" or "No" with keyboard. 

### ISSUE THREAD

**Issue by Elaws** [chhoumann/quickadd#165]
**Is your feature request related to a problem? Please describe.**
When using a `yesNoPrompt`, choice is selectable only via mouse, not via keyboard.

**Describe the solution you'd like**
Possibility to select `Yes` or `No` via keyboard (e.g. Tab or arrows).

**Comment by chhoumann** [comment]
Will be added in the next release. Thank you for submitting this FR!

**Comment by Elaws** [comment]
Hello @chhoumann : I'm not sure if yes no prompt is now selectable via keyboard ? When using keyboard, nothing appears to be selected using arrows.

Thanks !
