### ISSUE TITLE
[BUG] Android - TypeError: app.vault.adapter.getBasePath is not a function

### ISSUE THREAD

**Issue by chelming** [chhoumann/quickadd#167]
**Describe the bug**
I'm trying to run quickadd on my Android phone. I can find my macro that I've created (and verified that it works on desktop) but when I run it I get the following error:
```
Uncaught (in promise) TypeError: app.vault.adapter.getBasePath is not a function
    at getUserScript (eval at <anonymous> (app.js:1:1), <anonymous>:10399:41)
    at MacroChoiceEngine.executeUserScript (eval at <anonymous> (app.js:1:1), <anonymous>:11554:34)
    at MacroChoiceEngine.executeCommands (eval at <anonymous> (app.js:1:1), <anonymous>:11533:28)
    at MacroChoiceEngine.run (eval at <anonymous> (app.js:1:1), <anonymous>:11526:20)
    at ChoiceExecutor.onChooseMacroType (eval at <anonymous> (app.js:1:1), <anonymous>:15792:27)
    at async ChoiceExecutor.execute (eval at <anonymous> (app.js:1:1), <anonymous>:15768:17)
    at async Object.callback (eval at <anonymous> (app.js:1:1), <anonymous>:15944:21)
getUserScript @ VM515:10399
executeUserScript @ VM515:11554
executeCommands @ VM515:11533
run @ VM515:11526
onChooseMacroType @ VM515:15792
await in onChooseMacroType (async)
LL @ app.js:1
t.onChooseItem @ app.js:1
t.onChooseSuggestion @ app.js:1
t.selectSuggestion @ app.js:1
e.useSelectedItem @ app.js:1
e.onSuggestionClick @ app.js:1
s @ app.js:1
```

Interestingly I get almost the same error when I try to hit the gear icon for the user script step in my macro.
```
VM515:10399 Uncaught (in promise) TypeError: app.vault.adapter.getBasePath is not a function
    at getUserScript (eval at <anonymous> (app.js:1:1), <anonymous>:10399:41)
    at UserScriptCommand.configureScript (eval at <anonymous> (app.js:1:1), <anonymous>:14595:28)
    at eval (eval at <anonymous> (app.js:1:1), <anonymous>:224:20)
    at Array.forEach (<anonymous>)
    at eval (eval at <anonymous> (app.js:1:1), <anonymous>:223:31)
    at configureChoice (eval at <anonymous> (app.js:1:1), <anonymous>:13851:3)
    at HTMLSpanElement.click_handler (eval at <anonymous> (app.js:1:1), <anonymous>:13854:30)
``` 

**To Reproduce**
1. Open obsidian on and android phone
2. Open the command pallet
3. Type the name of your quickadd macro

**Expected behavior**
I expected it to run just like it does on desktop.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10, macOS 11.6.2 (works on both)

**Smartphone (please complete the following information):**
 - Device: Pixel 3a
 - OS: Android 12
 - Browser: Chrome (latest as of today)
 - Obsidian version 1.0.5

**Additional context**
Let me know if there's anything else I can offer or explain!

**Comment by chelming** [comment]
does it need to be switched to `this.app`?

I have no idea what I'm doing but looking at the API docs, class [app](https://github.com/obsidianmd/obsidian-api/blob/master/obsidian.d.ts#L268-L279) contains Class [vault](https://github.com/obsidianmd/obsidian-api/blob/master/obsidian.d.ts#L3242). [adapter](https://github.com/obsidianmd/obsidian-api/blob/master/obsidian.d.ts#L3242) is a dataadapter which has an [interface](https://github.com/obsidianmd/obsidian-api/blob/master/obsidian.d.ts#L590) and an [implementation](https://github.com/obsidianmd/obsidian-api/blob/master/obsidian.d.ts#L1089)?

The interface doesn't have a getBasePath method but the [implentation does](https://github.com/obsidianmd/obsidian-api/blob/master/obsidian.d.ts#L1098).

I have no idea what I'm doing though.

It's possible that [vaultPath](https://github.com/chhoumann/quickadd/blob/master/src/utility.ts#L172) in src/utility.ts just needs to become `this.app.vault.adapter.getBasePath()` based on the [API docs saying to use this.app](https://github.com/obsidianmd/obsidian-api/blob/master/README.md#the-app-is-organized-into-a-few-major-modules)?

**Comment by chelming** [comment]
oh snap. I just realized this is a dupe of #50

**Comment by chelming** [comment]
so, changing [vaultPath](https://github.com/chhoumann/quickadd/blob/master/src/utility.ts#L172) to `app.vault.adapter.basePath` is a thing and it works. buuuut then it fails because apparently the node require() API isn't available on mobile.

I updated [L172](https://github.com/chhoumann/quickadd/blob/master/src/utility.ts#L172) to 
```
if (window.require?.cache[window.require.resolve(filePath)]) {
```
and that got rid of the next error but now I'm stuck at: `QuickAdd: (ERROR) failed to load user script Templates/Komga.js.`

**Comment by chelming** [comment]
I've gotten so far as to be able to get the path, but not import() it.

I'm able to get the path but I'm not able to import it 😞 
`/storage/emulated/0/Obsidian/PersonalVault/Templates/Komga.js`

```
VM119:10413 GET http://localhost/storage/emulated/0/Obsidian/PersonalVault/Templates/Komga.js net::ERR_ABORTED 404 (OK)
```
```
VM119:15951 Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: http://localhost/storage/emulated/0/Obsidian/PersonalVault/Templates/Komga.js
await (async)
```

**Comment by chelming** [comment]
More updates. Even correcting the URI from http to file throws an error:
```
VM443:1 Not allowed to load local resource: file:///storage/emulated/0/Obsidian/PersonalVault/Templates/Komga.js
```

**Comment by Elaws** [comment]
Same problem here, related to #50 , really interested to follow.

**Comment by chelming** [comment]
lol I'm not sure how interesting I'd classify my ramblings.

The TL;DR appears to be that Android (potentially iOS too) doesn't allow you to `import()` a local resource. A workaround is probably to read the file and either `eval()` or `new Function()` it, but there's bound to be some issues with that like the .exports() used to communicate back to QuickApp.

**Comment by chhoumann** [comment]
Hey @chelming! Thank you for reporting.
I've made a fix that, from my tests, make scripts work on mobile as they do on desktop. I'll push the fix in the next update.

**Comment by chelming** [comment]
I'll do some debugging when I'm at a laptop but right now I can get the first prompt to appear when I run my macro but not the suggestion prompt afterwards.

**Comment by chhoumann** [comment]
> I'll do some debugging when I'm at a laptop but right now I can get the first prompt to appear when I run my macro but not the suggestion prompt afterwards.

Do you think you can share it with me? Then I'd be able to debug as well.

**Comment by chelming** [comment]
Sure thing, here's a gist of the JS file: https://gist.github.com/chelming/b8e4e58e6ad6d99f3380dda36f5de626

There's a demo site that you should be able to plug in to it: https://komga.org/guides/#demo
URL: https://demo.komga.org/
Username: demo@komga.org
Password: komga-demo

**Comment by chelming** [comment]
Thanks so much! It works and I'm so happy now!

**Comment by Elaws** [comment]
Hello,

I still get a `QuickAdd.app.vault.adapter.getBasePath is not a function` error on mobile, with Quickadd 0.5.0.
[
Here is the issue with more details.](https://github.com/chhoumann/quickadd/issues/195)

**Comment by chhoumann** [comment]
> Hello,
> 
> I still get a `QuickAdd.app.vault.adapter.getBasePath is not a function` error on mobile, with Quickadd 0.5.0. [ Here is the issue with more details.](https://github.com/chhoumann/quickadd/issues/195) (see Script 2)

Hi @Elaws,

I'll respond in the issue you opened. `getBasePath` is not used in QuickAdd anymore, anywhere, as it doesn't work on mobile.
