### ISSUE TITLE
[FEATURE REQUEST] Input text remains visible beyond the parameters of the box

### ISSUE THREAD

**Issue by Keys42** [chhoumann/quickadd#169]
**Is your feature request related to a problem? Please describe.**
My captures are sometimes longer than the input bar. After typing more than the width of the input bar , the text is no longer visible.

**Describe the solution you'd like**
I would like for the text to be visible in the input bar no matter how much I type. 

**Additional context**
I use this a lot for typing quick journal entries in other languages that I'm learning. Super helpful without having to open a note.

**Comment by chhoumann** [comment]
Hey! Thanks for the feature request.

I added a setting for multi-line inputs, which features a much larger box. Does this resolve the request for you, or are you looking for something else?

**Comment by Keys42** [comment]
Almost! Thanks for the multi-line input. Works really well for LTR languages like French, German Greek, or English. 

Unfortunately still facing the same issue with RTL languages like Arabic where the letters get stuck on the left side. Would it be possible to have this scroll left as well as right? 

I've attached a screenshot of RTL and LTR. The latter works well, but unfortunately the former still gets stuck. 

Thanks!

<img width="913" alt="RTL" src="https://user-images.githubusercontent.com/67223607/150416078-4478181d-eaae-4b9f-96c8-0de5f8bdc9fa.png">
<img width="926" alt="LTR" src="https://user-images.githubusercontent.com/67223607/150416090-6f1e7a08-307a-4cee-a740-1fcb9371e13b.png">
t

**Comment by chhoumann** [comment]
Issue with RTL text was raised again in #739 - fixed now :)
