### ISSUE TITLE
[BUG] note created from templates does not format string in source

### ISSUE THREAD

**Issue by HananoshikaYomaru** [chhoumann/quickadd#174]
**Describe the bug**
The note created from template does not format string in source. But the name is correctly formatted. Below is an example of my daily note, my daily note has the name and a header of `{{DATE:YYYY-MM-DD}}`.

<img width="501" alt="CleanShot 2022-01-21 at 00 24 17@2x" src="https://user-images.githubusercontent.com/43137033/150380117-f0d14a23-07c7-4faf-b1f5-a636090c7cbd.png">

This is not a template, this is a note created from template.

I think the reason is the content is created before the filename is changed. 

**To Reproduce**
1. create a capture with template, the template should have format string in the content. 
2. capture to a non-existing note

**Expected behavior**
The header should be correctly formatted to `2022-01-20`

**Desktop:**
 - macOs

**Comment by trojkat** [comment]
@HananoshikaYomaru try with `{{DATE:YYYY-MM-DD}}` (uppercase)

https://github.com/chhoumann/quickadd/blob/master/docs/FormatSyntax.md
