### ISSUE TITLE
[BUG] Template folder path does not parse variables nor does the file name support forward-slashes

### ISSUE THREAD

**Issue by DJBootyShark** [chhoumann/quickadd#176]
### Description: 
Template File path does not allow forward-slashes (i.e. example/example.md does not work but example.md does) nor does the folder path allow formatted variables (i.e. Journal/{{DATE:YYYY}} does not work but Journal/2022 does ) 

When putting a forward-slash into the file path Obsidian returns the following error 

`QuickAdd: (ERROR) Could not create file with template. Maybe 'PATH-TO-TEMPLATE' is an invalid template path?`

This happens regardless of the template used. When the forward-slash is removed the error likewise goes away, so it isn't a template issue but most likely a parsing issue with QuickAdd.

When you add just the {{DATE}} variable to the folder path it successfully creates a folder named {{DATE}} rather than parsing the date and using that. When you use a formatted variable such as {{DATE:YYYY}} in the folder path QuickAdd simply refuses to run that action without providing an error. Even when the action is bound to a hotkey the hotkey simply does not function.

### Reproduction: 
Input either a forward-slash into the file path or a formatted variable into the folder path of a template action.

### Expected behavior: 
Proper parsing of either one would solve this, as the goal is to properly parse variables into the file path. Being able to input Journal/{{DATE:YYYY}} into the folder path so that a folder labeled as the current year is made within the Journal folder and the subsequent template file is made within the year file. However being able to do so directly from the file name path would serve equally since the variables seem to parse correctly within the preview box.

### Operating Environment:
This problem seems system agnostic, I have tried on Windows and iOS with the same results.

**Comment by SlRvb** [comment]
+1 on this issue. It also doesn't work for `{{DATE:YYYY}}/{{VALUE:Title}}` in the **file name** input.
