### ISSUE TITLE
[FEATURE REQUEST] Duplicate template/capture/macro/multi

### ISSUE THREAD

**Issue by janpeeters70** [chhoumann/quickadd#178]
Thanks for your incredibly useful plugin. 

I think that a great addition to the plugin would be a duplicate button after the already created templates/captures/macros/multis. This would save a lot of time recreating Templates when they have only slight variations with already existing.

Thanks for considering.

**Comment by argenos** [comment]
Just wanted to add a +1 to this!

**Comment by Lulullia** [comment]
+1 !

**Comment by mrkuramoto** [comment]
Yes! +1

**Comment by erauner12** [comment]
+1

**Comment by chhoumann** [comment]
Hi everyone. Thank you, @janpeeters70 for making the suggestion, and everyone else for voting! This helped me prioritize this feature. It has just been released as part of v0.9.0 :)

**Comment by janpeeters70** [comment]
Thanks a lot for adding the feature!
