### ISSUE TITLE
"Append Link to open file in Capture" appends link to capture in the Open File

### ISSUE THREAD

**Issue by jowibou** [chhoumann/quickadd#19]
Thanks for a great plugIn. Very useful and well designed.
But to my mind, the "Append Link to open file in Capture" does the opposite of what I'd expect. 
It adds a link in the open file to whichever note I capured the text to. 
Doing what it says on the tin would be more useful, IMO.

**Comment by chhoumann** [comment]
Hey! Thank you.

You can actually do both. There's the format syntax `{{LINKCURRENT}}` which links to the page you're adding from.

Demo: 
![qP4j07DLIQ](https://user-images.githubusercontent.com/29108628/122744981-d3755780-d288-11eb-8d66-8824e20f94c0.gif)

**Comment by jowibou** [comment]
Thanks, that works. Though you might want to reword for clarity's sake. 
Also the "Prepend" option should say "append" since it puts it at the _end_ of the file; the default position at the top would be "prepend".
Is there any chance we could avoid having the whole path and just append the [[ShortLink]]. I'm sending text to cards in the Kanban PlugIn and having the whole path crowds the cards.
Again thanks for the plugin, these are just minor issues.

**Comment by chhoumann** [comment]
> Thanks, that works. Though you might want to reword for clarity's sake.

Agreed - done.
> Also the "Prepend" option should say "append" since it puts it at the _end_ of the file; the default position at the top would be "prepend".

Yep! You're right. Reworded to clarify.

> Is there any chance we could avoid having the whole path and just append the [[ShortLink]]. I'm sending text to cards in the Kanban PlugIn and having the whole path crowds the cards.
> Again thanks for the plugin, these are just minor issues.

Update 0.2.3 will use the Obsidian link generator rather than my own 'quick-fix' one. This should help. Please do tell me if it resolved the issue. =D

**Comment by jowibou** [comment]
THanks! That all works perfectly!
