### ISSUE TITLE
[BUG] Macros that call User scripts do not work on Obsidian mobile app.

### ISSUE THREAD

**Issue by brkwtnh** [chhoumann/quickadd#191]
**Describe the bug**
I created a user script and assigned it to Macro that shows several suggesters in turn to select a note type, input the file name, and finally create it. I referred to the example below, especially the function called "getBooks".
https://github.com/chhoumann/quickadd/blob/master/docs/Examples/Template_AutomaticBookNotesFromReadwise.md

But nothing happens on mobile app after having called the command despite that it successfully works on desktop.
Just in case, I tried the same process with another simpler script that only has a function to show a suggester. And again, it works on desktop but not on mobile app.

**To Reproduce**
1. Add a macro that calls your original script that returns a suggester. (User Scripts)
2. Make it available by setting it to the command or enabling Run on plugin load.
3. Call it on mobile app.
4. Get nothing.

**Screenshots**
These are some captures of reproducing on desktop. The first suggester does not appear in the first place on mobile.
![1](https://user-images.githubusercontent.com/86272619/152292013-2b440062-f259-408d-9230-01552cff4c6d.png)
![2](https://user-images.githubusercontent.com/86272619/152292007-903b6b27-1e71-4751-8cd3-9878f90e1a1b.png)
![3](https://user-images.githubusercontent.com/86272619/152292015-9f3df2bb-140d-48ea-9af6-2e8a6e07f4eb.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Smartphone (please complete the following information):**
 - Device: iPhoneXR
 - OS: iOS14.5

**Comment by chhoumann** [comment]
Hey @brkwtnh!
I've made a fix that, from my tests, make scripts work on mobile as they do on desktop. I'll push the fix in the next update.

**Comment by brkwtnh** [comment]
> Hey @brkwtnh! I've made a fix that, from my tests, make scripts work on mobile as they do on desktop. I'll push the fix in the next update.

Thank you very much @chhoumann for your quick response and fix!
I have just confirmed that it works on mobile.
