### ISSUE TITLE
[BUG] 0.4.22 release cannot be installed

### ISSUE THREAD

**Issue by pjeby** [chhoumann/quickadd#193]
**Describe the bug**
The manifest for 0.4.22 (and in the main branch) shows version 0.4.21, so Obsidian does not think a new version is available and does not offer to update.

Please note that fixing this will require changing **both** manifest.json versions.  (If only the trunk is changed, then Obsidian would download the new version, but since the release manifest says 0.4.21, Obsidian would keep thinking an update is needed.)

**Comment by chhoumann** [comment]
Thank you, @pjeby! I just pushed 0.5.0, which fixed this. :)
