### ISSUE TITLE
[BUG] cannot capture to the cursor position of an active file 

### ISSUE THREAD

**Issue by Ravenclawer** [chhoumann/quickadd#196]
**Describe the bug**
setting: 
![image](https://user-images.githubusercontent.com/73892411/152743040-f23eb36c-3c8e-4463-98bb-f0a8b528c384.png)

when using capture to active file, the capture function will produce error 
![Animation1](https://user-images.githubusercontent.com/73892411/152743296-57a62e1e-e1da-4d48-9f9b-4a13f94c0cf2.gif)

**To Reproduce**
1. add an quickadd capture option like in the previous section 
2. ctrl+p and search for the command
3. write any thing and press enter

**Expected behavior**
to put the thing you write to the current cursor position
**Screenshots**
![image](https://user-images.githubusercontent.com/73892411/152743619-af007fda-8c20-4b74-b8b2-e0b12abf9a58.png)

**Desktop (please complete the following information):**
windows 0.13.23
**Smartphone (please complete the following information):**
not test on mobile device
**Additional context**

**Comment by Ravenclawer** [comment]
the bug will go away if you open write to bottom of file 
![image](https://user-images.githubusercontent.com/73892411/152743923-1ac8ae3e-36f9-4531-9fc0-12bec5c1710a.png)
demo:
![Animation2](https://user-images.githubusercontent.com/73892411/152744344-ba9a6ba1-8d67-4693-bd22-22dc51cbefe1.gif)

**Comment by chhoumann** [comment]
Hi @Ravenclawer & @zerowidth!

Thank you for reporting this. I've just pushed an update which should fix the issue. Should be 0.18.2.
Can you confirm this on your end? Apologize for the inconvenience this may have caused!

**Comment by ianlhayes** [comment]
@chhoumann Long-time user, first-time caller! I can't speak for @Ravenclawer or @zerowidth, but I had the same issue with capturing to the cursor position, and it appears to be resolved with 0.18.2. Thanks for such a great plugin!

**Comment by chhoumann** [comment]
That's great to hear. Thank you for updating me, @ianlhayes! Glad you like the plugin as well :)

Considering this issue resolved.

**Comment by zerowidth** [comment]
I can confirm that this behavior is fixed. However, another bug... #440
