### ISSUE TITLE
QuickAdd: (ERROR) e.replace is not a function

### ISSUE THREAD

**Issue by aviskase** [chhoumann/quickadd#2]
I have a trouble making a plugin work. I configured a simple template, and this is what I see in the console right after Run quick add > Select choice

```
VM110:10316 QuickAdd: (ERROR) e.replace is not a function
logError    @   VM110:10316
eval    @   VM110:8253
logError    @   VM110:8253
run @   VM110:10099
async function (async)      
run @   VM110:10068
onChooseTemplateType    @   VM110:10276
onChooseItem    @   VM110:10253
t.onChooseSuggestion    @   app.js:1
t.selectSuggestion  @   app.js:1
e.useSelectedItem   @   app.js:1
(anonymous) @   app.js:1
e.handleKey @   app.js:1
e.onKeyEvent    @   app.js:1
```

I still see the prompt for filename, but the note isn't created.

quickadd version: 0.1.7
Obsidian version: v0.12.5 (installer version v0.12.3)
Platform: Linux (ubuntu)

Plugin's data.json: 
```
{"choices":[{"id":"6c2f5a21-11cc-4a97-b26b-80652ecc805a","name":"inbox_items","type":"Template","templatePath":"templates/test_temp.md","fileNameFormat":{"enabled":false,"format":""},"folder":{"enabled":false,"folders":[]},"openFileInNewTab":{"enabled":false,"direction":"vertical"},"appendLink":false,"incrementFileName":false,"openFile":true}],"macros":[]}
```

**Comment by aviskase** [comment]
Seems like it's failing on this method https://github.com/chhoumann/quickadd/blob/e2f74a9d6b90a43cbe504c117eb6c3be538c2d6e/src/engine/TemplateEngine.ts#L21

**Comment by aviskase** [comment]
Unrelated suggestion: would be great if you give an example of using this plugin together with Templater =)

**Comment by chhoumann** [comment]
Hey! Thank you very much. It's very appreciated. 😄 

I'm working on lots of examples, so I will surely do that!
