### ISSUE TITLE
"Insert after" sometimes generates error and causes entire file to be overwritten

### ISSUE THREAD

**Issue by cyrulnik** [chhoumann/quickadd#22]
I have one action set to "Insert after" a line called "# Daily Misc"

It works sometimes but other times it throws off an error that says "unable to find insert after line in file" -- and then it just overrides the entire file so that it contains just the text that is being added.

**Comment by chhoumann** [comment]
Should be fixed in the latest update. Thank you!

Please confirm. :)

**Comment by cyrulnik** [comment]
Seems to be working perfectly now. Thanks so much -- and thanks for this plugin generally. It's incredibly useful for me.

**Comment by chhoumann** [comment]
> Seems to be working perfectly now. Thanks so much -- and thanks for this plugin generally. It's incredibly useful for me.

Thank you! Glad you like it. :)
