### ISSUE TITLE
Enchanching the functionality of "File Name" field of Capture macro

### ISSUE THREAD

**Issue by Gaaruda** [chhoumann/quickadd#227]
**Is your feature request related to a problem? Please describe.**
how to add a task in a file(but at the time of chosing file to insert it may present us choice of files with a particular tag(preferred) or in a folder) using quickadd.

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/80031164/161895369-8ca42731-517b-4513-9511-492b37a86460.png)
writing the name of the folder like show in the image allow us to choose from the files present in the image
and writing like `tag: #project` would list all files with project tag.
I think this could be implemented with the help of dataview api.

**Comment by bondzula** [comment]
This would be such a cool feature, instead of having to specify capture for each file individually, we could just set the folder, then dynamically pick the right file.

My use case for this would be, I have a `people` folder, and I would like to use QuickAdd to capture agenda items as they arise for each person. Realistically, I don't have that many (around 10 or so), and could make a separate capture for all of them, but it just doesn't feel right. Is there maybe some other way to achieve this without having multiple captures that I'm not aware of?

**Comment by chhoumann** [comment]
Hi @Gaaruda & @bondzula

Thank you for the feature request!
I think this is a great feature. I've gone ahead and added it as per v0.19.0.
This release adds both Capture Anywhere (capture to folder) & Capture with Tag.

Here are the details about capturing to folders & capturing with tags:

### Capturing to folders
You can also type a **folder name** into the _Capture To_ field, and QuickAdd will ask you which file in the folder you'd like to capture to.
This also supports the [format syntax](/FormatSyntax.md). You can even write a filename in the suggester that opens, and it will create the file for you - assuming you have the _Create file if it doesn't exist_ setting enabled.

For example, you might have a folder called `CRM/people`. In this folder, you have a note for the people in your life. You can type `CRM/people` in the _Capture To_ field, and QuickAdd will ask you which file to capture to. You can then type `John Doe` in the suggester, and QuickAdd will create a file called `John Doe.md` in the `CRM/people` folder.

You could also write nothing - or `/` - in the _Capture To_ field. This will open the suggester with all of your files in it, and you can select or type the name of the file you want to capture to.

Capturing to a folder will show all files in that folder. This means that files in nested folders will also appear.

### Capturing to tags
Similarly, you can type a **tag name** in the _Capture To_ field, and QuickAdd will ask you which file to capture to, assuming the file has the tag you specify.

If you have a tag called `#people`, and you type `#people` in the _Capture To_ field, QuickAdd will ask you which file to capture to, assuming the file has the `#people` tag.
