### ISSUE TITLE
[BUG] Template path is not saved

### ISSUE THREAD

**Issue by wwwald** [chhoumann/quickadd#232]
**Describe the bug**
Relatively new user of Obsidian, so I'm still configuring and iterating a lot, also with the QuickAdd plugin.

When adding a new choice, I often see that the Template path value doesn't "stick" when being configured. I can change it, but when using the Quickadd command afterwards, I get an "invalid template path" error that still refers to the old value.

Restarting Obsidian sometimes helps: I can usually make one adjustment and that is applied correctly. But when making further adjustments, QuickAdd seems to get stuck on the old value again and I need another restart.

**To Reproduce**
1. Start Obsidian
2. Go to QuickAdd settings, add a new Choice and enable it as a command
3. Configure the "Template path" with a correct path to a template file
4. Close Settings dialogs
5. Ctrl+P → choose the new QuickAdd command
6. ERROR: "Please specify a path"... so it still assumes that my Template path  is empty (= the "old" value)

This is only one example with a newly configured Choice. Adjusting existing Choices gives me the same problem: QuickAdd reverts to using the old, previously configured value instead of the new one.

**Expected behavior**
QuickAdd should save the last entered Template path value?

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Obsidian 0.14.6, QuickAdd 0.5.5

**Comment by danieltomasz** [comment]
I am getting the same error "Please provide template path" ..., the same version of plugin + template

**Comment by danieltomasz** [comment]
I debugged it  even more, it seems that changing template without restarting Obsidian doesn't make template to change in Obsidian, only after restarting plugin/template it loads the last version of the template/last path

**Comment by wwwald** [comment]
@danieltomasz:  I don't fully understand your last comment - did you find a fix? Or did you confirm the buggy behavior, that restarts are always needed?

**Comment by SpxterWohlf** [comment]
I am having this issue as well, the dialog to chose a folder/file doesn't even pop up, and after restarting running the command does nothing.

**Comment by danieltomasz** [comment]
@wwwald 

1 First issue: ERROR: "Please specify a path" - I solved it by  manually editing the data file in the hidden plugin folder and removing  macro that hasn't specified a path
2. Later I  found that sometimes the quick-add doesn't  internally change the path to template even if I replace the path and point to another template (the old template containing templater commands was still loading, restart fixed this)
3. After restart I didn't thoroughly test but local changes in the same  template are reflected, I didn't try changing template file

**Comment by ThatNickPrice** [comment]
I have the `ERROR: "Please specify a path"` issue as well. Running the `QuickAdd: Run <macro name>` command fails, but the `QuickAdd: Run QuickAdd` -> `<macro name>` command works as expected.

It seems to happen when the option to add a command for a macro is toggled **before** the template path is defined. Works fine when the command option is toggled after.

Restarting Obsidian fixes it. Toggling the command option to disabled then enabled seems to fix it as well.

**Comment by AthreyaV** [comment]
this is still an issue, so I'm here to add some more info: quickadd doesn't recognize _any_ changes made until I restart the plugin (template path, file capture path, changes to macros, etc.) or cycle the command toggle.

As ghost stated, this seems to be some issue with the plugin re-caching only when the command toggle is messed with; if you have a functional template command for example and decide to change the template path, it will only reflect once you flip the command toggle on and off again.

**Comment by ixnet** [comment]
Hi every one!
I have the same issue on windows, and nothing helps to solve it from the solutions above.
Any hint would really appreciated, thanks

**Comment by ixnet** [comment]
It works okay with File name format option turned off:
![image](https://user-images.githubusercontent.com/9083398/204037276-f08087d4-112a-4483-ac27-bde081c54169.png)

**Comment by YunzBao** [comment]
You should reactive the choice after you modify it.

**Comment by z024966** [comment]
> It works okay with File name format option turned off: ![image](https://user-images.githubusercontent.com/9083398/204037276-f08087d4-112a-4483-ac27-bde081c54169.png)

Doesn't work regardless of where the setting is enabled or otherwise.

**Comment by ingewertwijn** [comment]
> 

I have the same situation

**Comment by ingewertwijn** [comment]
In my case, the problems disappeared when I used a hyphen between the {{date}} and {{value}} statements

**Comment by chhoumann** [comment]
Hello everyone. I really appreciate you taking the time to report in on this issue.

This bug has been fixed as of 0.11: https://github.com/chhoumann/quickadd/commit/fcbb8ee91e233a2a511934e6198bd67beef098f1

Commands are now updated whenever you save.
Thank you!
