### ISSUE TITLE
Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by Quorafind** [chhoumann/quickadd#24]
I did use macro to trigger macro sequences.

See the pic below:

![image](https://user-images.githubusercontent.com/13215013/122858288-9d011080-d34c-11eb-9a45-59b0a59b15b2.png)

And error comes.

If this caused this: ?

![image](https://user-images.githubusercontent.com/13215013/122858640-2d3f5580-d34d-11eb-95af-ff6c0f9897d1.png)

**Comment by chhoumann** [comment]
I've been trying to recreate this error with the same commands for a while, but am unable to. I'll keep trying, but please keep me updated to whether it continues or if there are any other updates.

**Comment by Quorafind** [comment]
@chhoumann did you try plugins on ver 0.12.6 ?

**Comment by chhoumann** [comment]
@Quorafind Yes that's the version I'm on. Would it be possible for you to share a screenshot of the error? I think that might help me debug.

**Comment by Quorafind** [comment]
![image](https://user-images.githubusercontent.com/13215013/123065680-f5660a00-d441-11eb-91eb-535026174940.png)

Here you go.

**Comment by Quorafind** [comment]
And I tried a blank vault, there isn't any problem, BUT when I closed all plugin except quickadd plugin, it still shows the same error when I trigger macro.

**Comment by chhoumann** [comment]
Thank you! I have pushed an update which might resolve the issue.
However, if it does not, could you try deleting the macro and creating it again?
I recently had to change how macro IDs functioned, so this may have caused this issue. My apologies!

**Comment by Quorafind** [comment]
I found the error happened in all my old vault, but when I created a new vault and then toggled anything one by one, and make it seems the same as my old vault's config, macros works. I think the problem isn't related to the plugin, maybe it related to Obsidian itself. Thanks for your hard job!

**Comment by chhoumann** [comment]
I'm glad to hear that it's been resolved. Thank you very much! =D
