### ISSUE TITLE
Problem with Templater template

### ISSUE THREAD

**Issue by cybexmind** [chhoumann/quickadd#25]
hi, after Obsidian update 0.12.5 and your last update, all the old template don't go right.
There are Parsing error in template now..
Can you check?

**Comment by chhoumann** [comment]
Hey! Which templates are not working?

**Comment by cybexmind** [comment]
This:
---
creation date: <% tp.file.creation_date() %>
modification date: <% tp.file.creation_date("dddd Do MMMM YYYY HH:mm:ss") %>
tags:<%*
var ris="";
// Attività
if(tp.file.path().contains("Attività")) {
ris=" todo";
}

// Obsidian
if(tp.file.path().contains("Obsidian")) {
ris=" obsidian";
}

// Note Giornaliere
if(tp.file.path().contains("📅 Note giornaliere")) {
ris=" todo, daily";
}

// GLS
if(tp.file.path().contains("GLS")) {
ris=" gls";
}

// Interessi
if(tp.file.path().contains("Interessi")) {
ris=" interessi";
}

// Python Risorsa
if(tp.file.path(true).contains("Programmazione/Python/"+tp.file.title+".md"))
{
ris=" python,risorsa";
};

// Windev Risorsa
if(tp.file.path(true).contains("Programmazione/Windev/"+tp.file.title+".md"))
{
ris=" windev,risorsa";
};

// Windev Applicazione
if(tp.file.path().contains("Windev/💾 Applicazioni/"+tp.file.title+".md")) {
ris=" windev/applicazione";
}

// Windev Applicazione Commerciale
if(tp.file.path().contains("Windev/💾
Applicazioni/Commerciale/"+tp.file.title+".md")) {
ris=" windev/applicazione, App_Commerciale";
}

// Windev Applicazione Aggiornamento Programmi
if(tp.file.path().contains("Windev/💾 Applicazioni/Aggiornamento
Programmi/"+tp.file.title+".md")) {
ris=" windev/applicazione, App_Aggiornamento_Programmi";
}

// Windev Applicazione Gestione Sinistri
if(tp.file.path().contains("Windev/💾 Applicazioni/Gestione
Sinistri/"+tp.file.title+".md")) {
ris=" windev/applicazione, App_Gestione_Sinistri";
}

// Windev Applicazione Visualizza Report
if(tp.file.path().contains("Windev/💾 Applicazioni/Visualizza
Report/"+tp.file.title+".md")) {
ris=" windev/applicazione, App_Visualizza_Report";
}

// WindevMobile Risorsa
if(tp.file.path().contains("Programmazione/WindevMobile/"+tp.file.title+".md"))
{
ris=" windevmobile,risorsa";
}
// Windev Applicazione
if(tp.file.path().contains("WindevMobile/💾
Applicazioni/"+tp.file.title+".md")) {
ris=" windevmobile/applicazione";
}

tR += ris;%>
---
# <% tp.file.title %>
<%*
// Attività
var ris="";
if(tp.file.path().contains("Attività")) {
ris=" - [ ] ";
}
// Note Gionaliere
if(tp.file.path().contains("📅 Note giornaliere")) {
ris="\n\
## Mattino \n\
- [ ] 09:00 Controllo programma lettura pesatrice Palmare \n\
- [ ] 13:00 break \n\
## Pomeriggio \n\
- [ ] 20:00 end \n";
}
tR += ris; %>



Il giorno mar 22 giu 2021 alle ore 18:13 Christian Bager Bach Houmann <
***@***.***> ha scritto:

**Comment by chhoumann** [comment]
This should be resolved in 0.2.7. Please confirm.

Thank you for reporting it!

**Comment by cybexmind** [comment]
Now all right. Thank you for quick response. QuickAdd is great plugin.
if in the future you could put more examples, especially for Capture and
Macro, it would be remarkable.

Il giorno mar 22 giu 2021 alle ore 18:54 Christian Bager Bach Houmann <
***@***.***> ha scritto:

**Comment by chhoumann** [comment]
Good to hear.
Yes, I'll provide some more examples soon!
