### ISSUE TITLE
[Bug] Some functions from Templater are called twice on creation

### ISSUE THREAD

**Issue by meskill** [chhoumann/quickadd#26]
Hello, thanks for the great plugin.

I'm using Templater and [tp.system.prompt](https://silentvoid13.github.io/Templater/docs/internal-variables-functions/internal-modules/system-module#documentation) in my templates and when I try to create new note using QuickAdd prompts to enter are showing 2 times and only last value is used in the final note.

Example of template (test.md):
```
<% tp.system.prompt('hello templater') %>
```

Settings for template in QuickAdd:
![image](https://user-images.githubusercontent.com/8974488/122974437-fb54e000-d39a-11eb-8e01-ffaeb2385865.png)

**Comment by chhoumann** [comment]
Hey! Thank you for your detailed report. This should be fixed in the latest version (0.2.8). Please confirm. =D

**Comment by meskill** [comment]
@chhoumann, I've tested latest version and I confirm the issue is fixed, thank you
