### ISSUE TITLE
[QUESTION] how to use {{TEMPLATE:}} syntax

### ISSUE THREAD

**Issue by GamerGirlandCo** [chhoumann/quickadd#265]
sorry if this is a stupid question... it says [here](https://github.com/chhoumann/quickadd/blob/master/docs/FormatSyntax.md) that `{{TEMPLATE:<TEMPLATEPATH>}}` allows you to include a template in your format.

i created a template to be used by a capture choice, that looks something like this:
```
---
title: {{VALUE:Title}}
type: {{VALUE:outline,story,ideas,tasklist}}
somevar: {{TEMPLATE:z/templater/testplate}}
---
```
however, `{{TEMPLATE:z/templater/testplate}}` doesn't change to the template contents. am i doing something wrong? should i not be using a `capture`? apologies once again, i'm really new to this plugin 😅

**Comment by NorthboundPaddler** [comment]
I also see this behavior using Obsidian 1.0.3 where I use a vanilla Template file for a template choice in this plugin. When I run QuickAdd, the template syntax `date:{{DATE}}` does not automatically populate as I'd expect when the note is created.

**Comment by stephenalandavis** [comment]
Add the file extension to the end, like so:

```
somevar: {{TEMPLATE:z/templater/testplate}}
```

**Comment by GamerGirlandCo** [comment]
turned on the Templates core plugin (since it was off for some reason) and it works like it should now.
