### ISSUE TITLE
[Bug] Cannot change command registration for commands in folders 

### ISSUE THREAD

**Issue by meskill** [chhoumann/quickadd#28]
Feature https://github.com/chhoumann/quickadd/issues/6 not working for commands inside folders

For example
![image](https://user-images.githubusercontent.com/8974488/123075124-9e037200-d420-11eb-875b-eb05962f1bc5.png)

Lightning icon are showing but pressing on it doesn't change anything. If you move command outside folder it works as expected

**Comment by chhoumann** [comment]
Thank you for your report!

This should be fixed in 0.2.9. Please confirm.

**Comment by meskill** [comment]
It is fixed, thanks
