### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by micwaab** [chhoumann/quickadd#281]
**Describe the bug**

2 Bugs:
1) When creating a new QuickAdd template command, in the field where I input the template file path, I do not get any auto suggestions as I start to type a template or folder name. Instead, I have to type the full path manually and from memory. 

2) After creating any new QuickAdd command, I must close Obsidian and reload before running the new command. If I don't, the newly created command always aborts due to an error. After closing and reloading Obsidian, there is never an error. 

**To Reproduce**
**bug 1**
1) Create a new QuickAdd template command. 
2) In the creation panel, enter a template file path. 
3) File path field remains blank even when I begin typing a valid file path. 

**bug 2**
1) Create any new QuickAdd command. 
2) Run command from command palette. 
3) Error notification appears and command aborts. 

**Expected behavior**
**bug 1**
I expect to see auto suggested template path options as I start typing. 

**bug 2**
I expect to be able to run a QuickAdd command after creating it without having to close and reload Obsidian. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac Monterey
 - Browser: Brave and Chrome
 - Version: all are the most current versions always 

**Smartphone (please complete the following information):**
 None

**Additional context**

**Comment by Finessest** [comment]
Same issue under macOS Monterey / Version 12.5.1 (21G83)

**Comment by chhoumann** [comment]
Hi @micwaab & @Finessest 

Thank you for reporting this!
I have identified and fixed both issues as of 0.11: https://github.com/chhoumann/quickadd/releases/tag/0.11.0
