### ISSUE TITLE
[Bug] citationsManager missing illegal file name character '?' for Windows

### ISSUE THREAD

**Issue by mnipshagen** [chhoumann/quickadd#286]
Hi!
I had an issue with a paper not working with the citation manager script and after some trial and error found that the example script is missing the '?' in the replacement function of illegal characters at https://github.com/chhoumann/quickadd/blob/2d2297dd6b2439b2b3f78f3920900aa9954f89cf/docs/Examples/Attachments/citationsManager.js#L84

Just adding a '\?' will fix that problem for the rare case you have a paper with a question mark in the title and are using {{VALUE:fileName}} in the macro.

**Comment by chhoumann** [comment]
Fixed in latest `citationsManager.js`. Thank you!
