### ISSUE TITLE
[BUG?] MACRO CHOICE: Workbench Plug-in Hotkeys  (0.2.10)

### ISSUE THREAD

**Issue by FelipeRearden** [chhoumann/quickadd#32]
Hello @chhoumann !!!

First of all, I just wanna thank you for everything that you have done for this community. All of yours plugins are a game-changer. 

I'm just getting started with Quickadd and my first road is about the MACRO CHOICE. 
- I'm using MACRO to automate my hotkeys workflow. Every workflow that I use more than one hotkey will be "transferred" to Quickadd.

I found one specific situation using 2 hotkeys from the [Workbench plug-in](https://github.com/ryanjamurphy/workbench-obsidian/issues) that I wanna share with you.

The HotKeys are: 
1 `Workbench: Copy the Current Line/Block to your Workbench`
2 `Workbench: Link the Current Line/Block into your Workbench`

-> The first hotkey copy the current line to the workbench note 
-> The second create a blockrefence and copy the path into the workbench note

I created a MACRO CHOICE and a MACRO like this:
![Screen Shot 2021-06-24 at 15 05 19](https://user-images.githubusercontent.com/85180696/123316860-b8fae280-d503-11eb-8755-feb2540886ad.png)

![Screen Shot 2021-06-24 at 15 08 10](https://user-images.githubusercontent.com/85180696/123316934-d334c080-d503-11eb-9770-3383d7275a24.png)

When I activate the Quickadd from the prompt, ONLY the SECOND hotkey of the MACRO is lanched
- As you can see, the 2 hotkeys are running, but only the second is working
![Screen Shot 2021-06-24 at 15 13 35](https://user-images.githubusercontent.com/85180696/123317080-fb242400-d503-11eb-9c2d-2c00fe49123d.png)

- Doing this same operation without Quickadd works 100% OK (that was my operation before Quickadd)
![Screen Shot 2021-06-24 at 15 18 06](https://user-images.githubusercontent.com/85180696/123317144-0aa36d00-d504-11eb-9f3b-20edea44b815.png)

Then I decided to investigate before writing to you. I did the following tests:
- Quickadd only with hotkey `Workbench: Copy the Current Line/Block to your Workbench` => 100% worked! 🟢
- Quickadd only with hotkey `Workbench: Link the Current Line/Block into your Workbench` => 100% worked!🟢
- Quickadd with 3 hotkeys `Workbench: Copy... + Show Outline Pane + Workbench: Link ... ` => fail 🔴  

I would be extremely grateful if you could take a look if this happens in your end. 

Let me know if you need more information.

Thanks for reading this and have a great day!

**Comment by chhoumann** [comment]
Hey @FelipeRearden! Thank you very much! Both for your praise and for your very detailed report.

I recreated the error, thanks to your description, and managed to fix it. I'm still working out what may be a good fix for issues like this one, as I'd be sad to put a hard limit of x milliseconds on every item in a macro.

In general, some plugins _really_ don't like when their commands are being executed too rapidly in succession. This is what happened here. I plan to add control flow and timers to macro execution, which should remedy these issues (as per #18).

Just wanted to give an update. I'll fix it tomorrow after work =D

**Comment by FelipeRearden** [comment]
Hello @chhoumann !

Thank you o much for your reply. Makes me very happy to know that my report helped to identify the issue. I tried my best to explain what I was facing! 

It seems to be something really specific. I did a MACRO with 5 commands without any issue. 

I’m sure that you will find the best solution to this “time”issues :)

Thanks for the update, I can sleep in peace now!

Great! I wish you a  fantastic day and a good workday!

**Comment by chhoumann** [comment]
In version 0.2.11, I have implemented a Wait command to address this.

Can you check if it works for you? 😁
![xAwl53WvmZ](https://user-images.githubusercontent.com/29108628/123476593-36564e00-d5fd-11eb-9871-d9249409cdd5.gif)

**Comment by FelipeRearden** [comment]
Hello @chhoumann !

0.2.12 solved this issue. It is absolutely perfect!!!!

Thank you so much for your hard work and attention to my post.

Have a great day and an amazing weekend!

**Comment by chhoumann** [comment]
Great! Thank you very much for your report, @FelipeRearden! Have a great weekend. =D
