### ISSUE TITLE
Not recognizing Template folder [BUG] 

### ISSUE THREAD

**Issue by menagerie198** [chhoumann/quickadd#320]
**Describe the bug**
Since v0.6.0 QA no longer recognises my Templates.

**To Reproduce**
update QA to v0.6.0
activate a QA to create a new doc from a template
modal pops up to name the new file, name it
an error message pops up saying 'QA could not create file with template: maybe 'Templates/Inputs/side_TP' is an invalid template path'
(it is not - version 0.5.5 works just fine )

**Expected behavior**
QA creates a file based on `side_TP`

**Screenshots**

**Desktop (please complete the following information):**
 - win 10

**Additional context**
rolling back to v0.5.5 (with no other changes) fixes the issue

**Comment by chhoumann** [comment]
Hi @menagerie198,
Thank you for your report!
I cannot seem to reproduce this issue. Could you provide me with the template & setup?

**Comment by menagerie198** [comment]
Here you go... this is the template:
`---
tags: ```js quickadd
const input = await this.quickAddApi.inputPrompt("Tags")
return input.replaceAll('#', '\r\n - ').toString();
```
 - Type-of-Note/sideNote
created: <% tp.date.now("YYYY-MM-DDTHH:mm ss zzzz") %>
lastModified: 
---
##### <% tp.date.now("dddd D MMMM YYYY") %>
# <% tp.file.title.split(/-\d{2} /)[1] %>

## <% tp.date.now("HHmm") %>
<% tp.file.cursor(1) %>
***
[[<% tp.date.now("YYYY-MM-DD") %>| « « Back]]`

here are are my QA settings:
![Screenshot 2022-11-19 120055](https://user-images.githubusercontent.com/7330436/202849851-8e862cac-968d-478a-bb88-29c49f90585b.jpg)
![Screenshot 2022-11-19 120003](https://user-images.githubusercontent.com/7330436/202849866-c693094d-5dcf-483d-97a2-290250c13477.jpg)

**Comment by NaturallyAsh** [comment]
I'm getting this error too. My macro has been working for weeks, but now it all of the sudden started throwing the "could not create file with template" error. My path has not changed. I recently updated to the latest Quickadd version yesterday. Maybe there's a bug? 

Mac Pro M1; latest Obsidian version

**Comment by menagerie198** [comment]
I managed to screen-cap the error messages I am getting -- might be some help?
![2022-11-20](https://user-images.githubusercontent.com/7330436/202903118-bd44e0f0-b6e3-4f75-81d9-d8a2462a1ce9.png)

**Comment by Lyatt77** [comment]
Getting this exact same error too, just updated to the new version

**Comment by chhoumann** [comment]
Thank you for providing the examples & errors!

Seems to be related to #321, as you had the inline script. Should be fixed now :)

**Comment by menagerie198** [comment]
Thanks Christian - all working as expected with v0.6.2. Great stuff!

**Comment by NaturallyAsh** [comment]
Works now for me too! Thanks for all your help and hard work!!
