### ISSUE TITLE
[BUG] Capture including jsquickadd "await" fails on v0.6

### ISSUE THREAD

**Issue by Ji11ard** [chhoumann/quickadd#321]
**Describe the bug**
When capturing to a file:

- using a {{TEMPLATE}} as the capture format; and
- that template has a "js quickadd" block; and
- that block contains an `await` of any kind - for example `await this.quickAddApi.suggester()`

Then QuickAdd fails without a popup error; and console reports "QuickAdd: (LOG) SyntaxError: await is only valid in async functions and the top level bodies of modules". 

**Expected behavior**
Prior to latest release, code executed as expected. 

**Desktop (please complete the following information):**
 - OS: MacOS Ventura
 - Hardware: Apple M1
 - Obsidian v1.0.3
 - QA v0.6.1

**Additional context**
I have also tried:

- Rolling back to v0.5.5 - code executes correctly as normal. 
- On a different PC (Apple Intel) - same error.
- Running same file without any await statements - remaining code executes correctly. 
- Using QA to capture, but running await statements inside a Templater codeblock instead - code executes correctly.

I suspect this error is _not_ directly related to [Issue 320 - unrecognised template folder](https://github.com/chhoumann/quickadd/issues/320). When I use my file as a Template (instead of a Capture), I get Issue 320 instead - so I suspect that Template choices can't find the template file... while Capture choices do find the template file, but don't see `js quickadd` blocks as being async or top-level for some reason.

**Comment by chhoumann** [comment]
Hi @Ji11ard 

Thank you for reporting this! Looks like the move to a new bundler broke inline scripts.
Should be fixed now. :)

**Comment by Vyeche** [comment]
After the v0.62 seeing the following error using macro templates.
@chhoumann 
```
const macroEngine = await new MacroChoiceEngine(this.app, this.plugin, macroChoice, this.plugin.settings.macros, this, this.variables);

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'settings')
    at ChoiceExecutor.onChooseMacroType (plugin:quickadd:37345:101)
    at ChoiceExecutor.execute (plugin:quickadd:37320:20)
    at ChoiceSuggester.onChooseItem (plugin:quickadd:37291:33)
    at ChoiceSuggester.t.onChooseSuggestion (app.js:1:1561562)
    at ChoiceSuggester.t.selectSuggestion (app.js:1:1561112)
    at e.useSelectedItem (app.js:1:1515204)
    at Object.func (app.js:1:1513919)
    at e.handleKey (app.js:1:1019276)
    at e.onKeyEvent (app.js:1:1020514)
```

**Comment by chhoumann** [comment]
Hi @Vyeche,
Thank you for mentioning this. Just released an update which should fix it :)
