### ISSUE TITLE
[BUG] Unable to create macros with UserScripts

### ISSUE THREAD

**Issue by tauren** [chhoumann/quickadd#323]
**Describe the bug**
Adding UserScript creates macro step with name of `undefined`

**To Reproduce**
1. Go to MacroManager
2. Click on Add Macro
3. Select Configure on added macro
5. Select user script and click Add
6. Item is added as `1. undefined`
7. Attempting to execute macro results in console error

**Expected behavior**
Macro step should be added with expected name

**Screenshots**

![image](https://user-images.githubusercontent.com/282084/203434445-77bd78cb-6f20-45b7-9657-4866e4fe199f.png)

![image](https://user-images.githubusercontent.com/282084/203434386-366068b5-27cb-4ef4-8a6f-3af0b46b50a9.png)

**Desktop:**
 - OS: MacOS 12.0.1 (21A559)
 - Browser Chrome Version 106.0.5249.119
 - QuickAdd 0.6.2

**Additional context**

I traced the code in Chrome debugger and it appears that the call to `Command.super()` in the `UserScript` constructor fails to set the name. The code looks right to me, so I'm not sure what is actually happening.

```
// src/types/macros/UserScript.ts
var UserScript = class extends Command {
  name;
  path;
  type;
  settings;
  constructor(name, path) {
    super(name, "UserScript" /* UserScript */); // <<<< Doesn't set this.name to value of name 
    this.path = path;
    this.settings = {};
  }
};
```

Debugging where the console error is thrown appears to be the result `this.plugin` being undefined:
![image](https://user-images.githubusercontent.com/282084/203436059-ffdce105-5a35-455e-9569-0abb1b8cd6d4.png)

**Comment by ThadySenior** [comment]
I have this exact issue trying to use the 'movies' script as detailed in this guide: https://minimal.guide/Guides/Create+a+movie+database

**Comment by chhoumann** [comment]
Thank you for reporting this & doing some debugging, @tauren! It helped get started on the issue.

Seems to be a build target that broke it.
I released a new update that should fix this issue.
