### ISSUE TITLE
[BUG] can't add obsidian commands to macros

### ISSUE THREAD

**Issue by Mahgozar** [chhoumann/quickadd#324]
**Describe the bug**
when creating new macros on the desktop version when I want to search for a command the suggestion doesn't work and I can't add any obsidian commands to the macro 
**Screenshots**
![image](https://user-images.githubusercontent.com/54596777/203542140-af7c6e9e-1182-42a3-af6f-ac972a7920fd.png)

**Comment by chhoumann** [comment]
Hi @Mahgozar,
Thank you for reporting this!

I just released a new update that I believe fixes this issue. Can you check? :)

**Comment by Mahgozar** [comment]
@chhoumann it's fixed thank you!

**Comment by chhoumann** [comment]
Great to hear. Thank you for checking, @Mahgozar!
