### ISSUE TITLE
[BUG] MACRO - Editing Obsidian Command

### ISSUE THREAD

**Issue by FelipeRearden** [chhoumann/quickadd#33]
Hello again @chhoumann !!!

The following MACRO has 5 Obsidian commands in this order: A - B - C - D - E 
![Screen Shot 2021-06-24 at 15 34 25](https://user-images.githubusercontent.com/85180696/123399019-86d89780-d57a-11eb-9e9b-422c3eec7595.png)

A few days later, I decided to change the order of the same MACRO to: B - C - D - E - A
![Screen Shot 2021-06-24 at 15 37 54](https://user-images.githubusercontent.com/85180696/123399059-8fc96900-d57a-11eb-8695-dcfa1dc76e66.png)

I close the window and when I come back, the order is again: A - B - C - D - E  
![Screen Shot 2021-06-24 at 15 35 03](https://user-images.githubusercontent.com/85180696/123399231-be474400-d57a-11eb-939f-8bf7d9268aec.png)

And the MACRO is respecting the A - B - C - D - E order when running.

I hope you could reproduce on you end. 
Have a great day!

**Comment by chhoumann** [comment]
Thank you very much! I have addressed this in 0.2.11. Please confirm if this has been fixed for you.

**Comment by FelipeRearden** [comment]
Hello @chhoumann!

I confirm that 0.2.12 fix the order issue. Now I can change the Obsidian commands position!!!!

The MACRO is amazing. I'm having a great time using it.

Thank you again @chhoumann !!!!! I wish you the best!

**Comment by chhoumann** [comment]
I'm glad to hear that it's resolved, @FelipeRearden. Thank you, and I wish you the best, too. :)
