### ISSUE TITLE
[BUG] Capture Choice does not work without a restart

### ISSUE THREAD

**Issue by d80harri** [chhoumann/quickadd#347]
**Describe the bug**
When creating a capture choice and using it later on a notification shows up "Please provide a capture path for". The capture will not be executed.

**To Reproduce**
1. Create a capture choice (in my case add a new line at the end of a predefined file)
2. Create shortcut for this capture
3. Hit the short-cut
4. Enter a value and hit enter

**Expected behavior**
A new line should be added at the end of the file

**Screenshots**
![image](https://user-images.githubusercontent.com/148149/207428460-9dbe3ffd-2946-4782-8925-d3e5d4f7977f.png)
![image](https://user-images.githubusercontent.com/148149/207428519-d3833c04-fe12-4ae5-abf4-51a1a6dc74cc.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser chrome
 - Version 108.0.5359.94 (Official Build) (64-bit)

**Additional context**
- Seems to be a duplicate of https://github.com/chhoumann/quickadd/issues/62
- I noticed that after restarting Obsidion everything works as expected
- After I restarted Obsidian I edited the capture once again and changed the file to write to. When testing the capture the new line is still written to the old file. Restarting again fixed that.

**Comment by jshph** [comment]
I hit the lightning bolt twice (turn off and back on) to update the shortcut; does this work for you?

**Comment by chhoumann** [comment]
Hi @d80harri 

Thank you for the report!

I was able to reproduce this, and then shortly after fix it.
So it should be fixed now.
