### ISSUE TITLE
Template path being appended to file location

### ISSUE THREAD

**Issue by LaP0573** [chhoumann/quickadd#35]
It seems that for a template entry, the template path is being appended to the file location. For example, if the template path is `utils/templates/Cactus.md` (btw the plugin isn't auto suggesting my templates/ folder for some reason, only my templater/ folder), and the file folder location is `🍃 leafs` (the folder name has an emoji in it), and the file name is `{{DATE:YYYYMMDDHHMMSS}} {{VALUE}}` I get this error when trying to trigger it :

`Error: ENOENT: no such file or directory, open 'C:\PathToVault\🍃 leafs\202106260936 utils\templates\Cactus.md'`

However if for the folder I put `/🍃 leafs` (so as an absolute path with a slash), it seems to solve the issue.

Any clue where the problem might be coming from?

**Comment by chhoumann** [comment]
This should be fixed in 0.2.12. Can you check?

Thank you for your report!

**Comment by LaP0573** [comment]
It works, well done!
