### ISSUE TITLE
[BUG] Template's {{time}} variable is ignored when creating a new note from a template using the Capture action

### ISSUE THREAD

**Issue by Bloodsucker** [chhoumann/quickadd#364]
**Describe the bug**
If a Capture action attempts to create a new note from a template that includes the `{{time}}` variable, it is ignored and no replacement occurs. This issue occurs when the Capture settings are configured with "Create file if it doesn't exist" enabled and "Create file with given template" is selected, with a template that includes the `{{time}}` variable. However, if the same template is inserted manually, the `{{time}}` variable is correctly replaced. Additionally, the `{{date}}` variable is replaced without any issues.

**To Reproduce**
1. Create a template that includes the `{{time}}` and `{{date}}` variables.
2. Configure a new Capture action in the plugin
3. Select a destination path that you know doesn't contain a note yet.
4. Enable the option "Create file if it doesn't exist" in the Capture settings.
5. Select the template created in step 1 as the "Create file with given template" option.
6. Run the Capture action so that it attempts to create a new note using the template.
7. Observe that while the `{{date}}` variable is replaced, the `{{time}}` variable is not."

**Expected behavior**
When creating a new note from a template using the Capture action, the `{{time}}` variable should be replaced with the current time, just like the `{{date}}` variable is replaced with the current date.

**Screenshots**

--

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser --
 - Version: 13.1

**Additional context**

--

**Comment by masoniis** [comment]
I'm getting this as well. Date is working correctly, but not time. Note that {{title}} is another that is not working correctly for me, also on MacOS.

**Comment by acdesigns** [comment]
Just to add that I'm getting the same thing on Windows 11, all the latest updates are done as well.

**Comment by Bloodsucker** [comment]
The workaround for me is to use Templater plugin which everyone that use plugins typically has it already enabled. So instead of using `{{time}}` you should use `<% tp.date.now("HH:mm") %>`

**Comment by chhoumann** [comment]
Hey! Thank you for filing this issue.

Please see here:
https://github.com/chhoumann/quickadd/issues/276

I'm not against making `{{time}}`, but you can get the exact same result with `{{date:HH:mm}}`.

**Comment by chhoumann** [comment]
And, of course, @Bloodsucker's method is perfectly valid as well.
