### ISSUE TITLE
[Feature Request] Hotkey for multi

### ISSUE THREAD

**Issue by LaP0573** [chhoumann/quickadd#37]
With the previous quickadd (the non-plugin version), I simulated the multi item (by making a quickadd script for which each items calls another one), and with the "hotkey for templater" plugin I was able to assign hotkeys to submenus.

For example my main menu is :
- Add
- Open
- XXX
- YYY

Which I open with ctrl + space (I can do that currently with the plugin)
But in addition to that, I bind the Add menu (which opens a submenu with lots of add possibilities) to ctrl + n to override Obsidian's. 

To allow this, I think that ideally the QuickAdd plugin should allow defining hotkeys for any of the items (including Multi) to trigger them independently.

Do you think that would be feasible ? Sorry for the influx of tickets btw, I've been moving my configuration from the old non-plugin version to the plugin version haha

**Comment by chhoumann** [comment]
Added in 0.2.13! 😄
