### ISSUE TITLE
[BUG] Command not updating after change

### ISSUE THREAD

**Issue by ThomJ130** [chhoumann/quickadd#373]
**Describe the bug**
If you have a command, and you modify that command, the command will not update unless your remove it and add it again (by unselecting and reselecting the lightning bolt.)

**To Reproduce**
1. Go to QuickAdd settings
2. Add new template "test" choice
3. Set "test" choice to be a command
4. Go to your note, open command pallet (`CTRL+P`), and type in "test"
5. Now, return to QuickAdd settings
6. Update the name of the choice to "somethingElse"
7. Repeat step 4 with "somethingElse" and notice that it will not show

**Expected behavior**
The command does not update with its new name. This is also true with behavior (so if you changed what the command does, it will not execute that new functionality until you refresh the command setting.) 

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome (but I use the desktop app...)
 - Version: Obsidian v1.1.9, QuickAdd v0.8.0

**Work Around**
If you have this issue, you can fix it without deleting your command. Simply uncheck and check the lightning bolt toggle to disable/enable the command. It will work as expected after doing so.

**Comment by chhoumann** [comment]
Hi @ThomJ130 

Thank you for reporting this!
The issue should be resolved as of 0.11: https://github.com/chhoumann/quickadd/commit/7ff60f219f27c2724ce686f8025051bf28e6bdb5
