### ISSUE TITLE
[FEATURE REQUEST] Access to {{VARIABLE:name}} in JavaScript blocks of captures.

### ISSUE THREAD

**Issue by silvio** [chhoumann/quickadd#377]
Maybe this is already possible and I just don't know.
It would be good to be able to access variables of the input mask in the javascrip block.

The background is that I use QuickAdd to collect sayings/quotes and then want to reference them. The quotes are stored in call-out boxes with a title. The title should also be the reference link. Here is my attempt:

    > [!quote] {{VALUE:title}}
    > {{VALUE:text}}
    > -- {{VALUE:author}}
    ```js quickadd
    const value = "{{VALUE:title}}";
    reformated = value.replace(/[^A-Z0-9]+/ig, "-");
    return `^${reformated}`;
    ```

The result should something like this:

    > [!quote] chaos nature order man
    > Chaos was the law of nature; Order was the dream of man.
    > -- Henry Adams
    ^chaos-nature-order-man

I tried several combinations with `${`/`${{`/`${name`/....

**Comment by chhoumann** [comment]
Here's how you can do it:

````markdown
> [!quote] {{VALUE:title}}
> {{VALUE:text}}
> -- {{VALUE:author}}
```js quickadd
const title = await this.quickAddApi.inputPrompt("title");
reformated = title.replace(/[^A-Z0-9]+/ig, "-");
this.variables.title = `^${reformated}`;
```
````

Inline scripts are parsed and executed before anything else, so using `{{VALUE:title}} and then grabbing `this.variables.title`  isn't possible, as it won't have gotten the value yet. So instead, you'd ask for the title, do the replacement action, and then set the variable, which is then used above.

**Comment by silvio** [comment]
Hi @chhoumann.

Thanks for your answer.

I wanted to use the title to create the block reference (last line, preceded by `^tile-with-hyphens` ) so that it is recognizably associated with the title.
Besides, this saves me a bit of extra manual typing and I don't have to ask about the reference.

Then this probably won't work with QuickAdd, will it?

**Comment by chhoumann** [comment]
Hmm. When I try, it's only asking me for the title once. I imagine you're trying to use `{{VALUE:title}}` in a template?

If so, then a macro is suitable. You can use a macro to prompt for the input first, format it, and then you can use `{{VALUE:title}}` in the remaining steps.

E.g. have a script like this one in your vault `script.js`:
```js
module.exports = async function(params) {
    const title = await params.quickAddApi.inputPrompt('Enter a title');
    const reformatted = title.replace(/[^A-Z0-9]+/ig, "-");

    params.variables['title'] = reformatted;
}
```

Quote template, `templates/quote.md`:
```markdown
> [!quote] ^{{VALUE:title}}
> {{VALUE:text}}
> -- {{VALUE:author}}
```

And then have a macro like this:
1. script
2. template

![Obsidian_ZN1b2KU2gI](https://user-images.githubusercontent.com/29108628/217309206-2af2121b-2a9d-49cf-b42c-6ca07b17a361.gif)

**Comment by silvio** [comment]
@chhoumann Thanks. Usage of Macros was not in my mind :-)
It is exactly what I want.

Thanks!
