### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by acdesigns** [chhoumann/quickadd#384]
**Describe the bug**
"Insert after" + "create line if not found" do not work. The values are simply added to the bottom of the file, no matter the which headings are there previously.

**To Reproduce**
1. Go to Quick Add plugin
2. Create new Capture
3. Created using: Daily note name, specific template (these all work perfectly)
4. Scroll down to Insert after and toggle on
5. Add line name to find (with or without heading syntax doesn't make a difference)
6. Scroll down to create line if not found and toggle on
7. Input value code and execute function using Command+P

**Expected behavior**
I expect the specified line to be created at the bottom of the specified note and the values created underneath

**Screenshots**
<img width="777" alt="image" src="https://user-images.githubusercontent.com/59508042/218516021-852c0f99-3f5e-4ce0-bee9-2659718c19f0.png">
<img width="777" alt="Screenshot 2023-02-13 at 11 42 48 AM" src="https://user-images.githubusercontent.com/59508042/218519109-a8c18757-a80e-4b2a-ab04-3a5ac9a2edb0.png">

**Desktop (please complete the following information):**
 - OS: iOS and Windows
 - Quick Add Version 0.9.1

**Comment by chhoumann** [comment]
Hi @acdesigns 

Thank you very much for reporting this!
From my testing, it seems that `Write to bottom of file` conflicts with `Insert after`.

If you disable the first option & just keep the latter two, it should be fine.

So, as in the image, if you disable (1), but keep your settings for (2), it should work.
![image](https://user-images.githubusercontent.com/29108628/220291270-226555d3-3dd5-485f-bd1c-4b3066b04bcf.png)

But I think it's a settings conflict we're seeing here. Insert after & `Write to bottom of file` should be mutually exclusive.
