### ISSUE TITLE
[Bug] Capture doesn't aplly Templater templates on new file creation

### ISSUE THREAD

**Issue by meskill** [chhoumann/quickadd#39]
I'm using Templater in my templates for daily notes.

Here is my configuration to Capture command to add new task in today note:
![image](https://user-images.githubusercontent.com/8974488/123510976-4ca8ec00-d687-11eb-80db-01ba984e7b06.png)

If there is no today note it will be created but templates won't apply leaving `<% tp.web.daily_quote() %>` in file as is

**Comment by chhoumann** [comment]
Hey! This should be fixed in 0.2.13. Could you check?

At least, I am no longer able to reproduce the issue.

**Comment by meskill** [comment]
@chhoumann Great job, once again! Thank you
