### ISSUE TITLE
Calling `checkboxPrompt(...)` from inline script results in the top-most toggle hiding the `X` button

### ISSUE THREAD

**Issue by JulianBroudy** [chhoumann/quickadd#393]
**Describe the bug**
When calling `this.quickAddApi.checkboxPrompt(<prompt description>);`  the GUI doesn't look good:

**To Reproduce**
1. Create new capture.
2. Select capture to active file.
3. Select write to bottom of file.
4. Enable capture format.
5. Insert either of the following scripts then execute it:
```js quickadd
    // Option #1
    const options = ["Priority", "Due Date", "Scheduled Date", "Start Date", "Recurrence"];
    const selectedOptions = await this.quickAddApi.checkboxPrompt(options, []);

    // Option #2
    const options = ["", "Priority", "Due Date", "Scheduled Date", "Start Date", "Recurrence"];
    const selectedOptions = await this.quickAddApi.checkboxPrompt(options, []);
```

**Expected behavior**
To see the `X` button.

**Screenshots**
![image](https://user-images.githubusercontent.com/46682375/220185866-ad55f88f-3907-4f5f-bd0c-48d711a3e7b7.png)
![image](https://user-images.githubusercontent.com/46682375/220185876-e5aa03f9-160b-41de-849e-50f79e51ab02.png)

**Desktop (please complete the following information):**
 - OS: Windows (don't know if on Android it is also hidden but it look ok)

**Comment by chhoumann** [comment]
Hi @JulianBroudy 

Thank you for reporting this! This is what happens when I do styling with a theme on lol.

Should be fixed in the latest release.
