### ISSUE TITLE
[Feature request] Is it doable that allow {select} variable in template?

### ISSUE THREAD

**Issue by Quorafind** [chhoumann/quickadd#4]
When I want to select a range of text, and then I want quick add it to my kanban or other notes.

if it is doable to make current select as a variable like {select}？

**Comment by chhoumann** [comment]
Hey! Thanks for the suggestion.

I adapted `{{VALUE}}` to do this. If any text is selected, `{{VALUE}}` will get it. If not, you'll be prompted as usual.
