### ISSUE TITLE
[BUG] Migrating was unsuccessful

### ISSUE THREAD

**Issue by sarantsatsral-qy** [chhoumann/quickadd#405]
**Describe the bug**
I update Quickadd and it says ```Migration `incrementFileNameSettingMoveToDefayultBehavior' dan `mutualExclusionInsertAfterAndWriteToBottomOfFile` was unsuccessful```

**To Reproduce**
1. Go to Community Plugins
2. Click on check on updates

**Expected behavior**
To be able to update Quickadd

**Screenshots**
![image](https://user-images.githubusercontent.com/30141705/222307845-3d2da18c-4e4e-4171-a70e-f40bf023c619.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Intel(R) Core(TM) i3-4150 CPU @ 3.50GHz   3.50 GHz RAM 12GB
 - Browser: Firefox
 - Version: 110.0.1

**Additional context**
Thank you, I am so grateful for your recent updates.

**Comment by chhoumann** [comment]
Hey @sarantsatsral-qy 

Thank you! I've just pushed a fix which will be available in the latest update.

**Comment by sarantsatsral-qy** [comment]
@chhoumann I should be the one who thank you. You updated it right away :)
