### ISSUE TITLE
"Toggle pin" doesn't work in macro[BUG] 

### ISSUE THREAD

**Issue by Smitty010** [chhoumann/quickadd#406]
**Describe the bug**
I can believe it's something i'm doing, but I can't get the following macro to work:

![image](https://user-images.githubusercontent.com/3760075/222940594-b6040bcf-2c13-483e-adf9-4404417ec71b.png)

The daily note opens fine.  However, the toggle never happens.  I tried with no delay and various delays up to 5 seconds.  The results don't change

**To Reproduce**
1. Create the macro as shown above
2. Use the command palette to execute the macro from QuickAdd

**Expected behavior**
I would expect that the daily note opens and then the pin is toggled.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] : Windows 11
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] latest

**Smartphone (please complete the following information):**

**Additional context**
Obsidian: 1.1.16
QuickAdd 0.11.6
I believe these are both the latest versions.

**Comment by FelipeRearden** [comment]
Trying to help here ....

Maybe this issue is because the note is open but is not active **focused** before apply the PIN command. 

When you execute this command from a previous note opened did you have this issue?

**Comment by Smitty010** [comment]
I understand what you are saying about whether the note has focus.  What I tried today was using the macro (which still includes the toggle pin) to open the note.  Doesn't pin the note.  Without doing anything else, I immediately did a ctrl-p (control palette) and selected the toggle pin.  That did pin the note.

**Comment by chhoumann** [comment]
Hmm... I'm using the exact same setup, but not getting any errors.
![image](https://user-images.githubusercontent.com/29108628/224295662-9aacacc6-79cb-442e-8ea5-a25fcc85a0d3.png)

After 5 seconds, the note is pinned.

Does any other command get run after the 5 seconds, if you try inserting one? E.g. splitting panes or something, as that's very visible.

**Comment by Smitty010** [comment]
And today, it's working.  I have noticed that sometimes QuickAdd doesn't recognize changes in configuration until I restart Obsidian (at least that's my impression).  I played with it this morning some more and I think I've convinced myself that the delay (wait) is necessary and 500ms is sufficient.  Regardless, I agree that it is working.  I will close based on that.

**Comment by chhoumann** [comment]
Great to hear. 

I'm working through the list of issues so any saving issues should be fixed in time. I've already fixed some of them, so looking forward to a more consistent experience soon.
