### ISSUE TITLE
[Feature Request] Calling templates from code

### ISSUE THREAD

**Issue by LaP0573** [chhoumann/quickadd#41]
Right now you can call a user script (macro) from a QuickAdd menu.

The other way around could be useful (i.e you're in a user script, and you trigger a QuickAdd template).

My use case is that some of my menus can not be entirely build with QuickAdd. For example I have a "smart context" menu that is a QuickAdd entry that fires a user script (through a hotkey). That user script analyzes the currently open file and offers options relevant to the file. Some of these options are user scripts, so it's all good, but some other are options I've already got setup within QuickAdd (like a Template option).

In this case, some way to refer & fire a QuickAdd menu/option would be ideal. Is that something that you could consider?

**Comment by chhoumann** [comment]
Implemented in 0.3.0 :)
