### ISSUE TITLE
"unable to get current file path"

### ISSUE THREAD

**Issue by pad-mac** [chhoumann/quickadd#411]
Since the last update QuickAdd seems to always try to get the currently open file path to execute any command. So when i use a command when there is no file open this error occurs. This didn't use to be the case, as i often would use my commands from outside Obsidian through Advanced URI (especially handy on mobile). 

This error happens even though i haven't specified in any macro to copy or insert the current file path, so it should not be relevant to file creation. So it appears necessary to open any random file to be able to use QuickAdd. Can anyone confirm this is a new issue? I suspected something like Templater automatically running the current file path query, but the problem persisted when disabling it.

Reproduce:
- Create a new QuickAdd template
- Create an empty template file and assign
- Close any opened files (New tab page)
- Run command from command palette

![grafik](https://user-images.githubusercontent.com/10145613/223474044-6f8fe1b8-fce5-4c5c-b9f2-d41cb0a83882.png)

**Comment by chhoumann** [comment]
Hey! This should be fixed in the latest release. Thank you for reporting!
Please do tell me if I've missed something :)

**Comment by pad-mac** [comment]
coool, thx a lot for the lightning fast reaction!
