### ISSUE TITLE
[BUG] Link is not created when file already exists

### ISSUE THREAD

**Issue by OnkelTem** [chhoumann/quickadd#412]
**Describe the bug**

When the file being created already exists, link is not set at all.

**To Reproduce**

1. Create new template and enable it as QuickAdd action. Configure **Set default behavior if file already exists** like this:

![image](https://user-images.githubusercontent.com/114060/223506553-69066f3b-9f04-48cd-be2d-0c0b3ecdeb44.png)

3. Select some text and run the action. File should be created and link should be set.
4. Now remove the link and try to create it again. In the popup pick the **Nothing** option:

![image](https://user-images.githubusercontent.com/114060/223506184-fcad7c86-4846-49a5-81cc-dd5e7b21a097.png)

5. File gets opened, but no link is created.

**Expected behavior**

If file exists, link should be created. **That's how QuickAdd worked before.**

```
SYSTEM INFO:
	Obsidian version: v1.1.16
	Installer version: v1.1.9
	Operating system: #74-Ubuntu SMP Wed Feb 22 14:14:39 UTC 2023 5.15.0-67-generic
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: none
	Snippets enabled: 2
	Restricted mode: off
	Plugins installed: 11
	Plugins enabled: 10
		1: Markdown prettifier v0.1.3
		2: Natural Language Dates v0.6.1
		3: Hotkeys++ v0.2.7
		4: Folder Note v0.7.3
		5: Templater v1.16.0
		6: QuickAdd v0.11.4
		7: Dataview v0.5.55
		8: Cycle through Panes v0.1.0
		9: Pane Relief v0.4.1
		10: Image Toolkit v1.3.1


```

**Comment by chhoumann** [comment]
Hey! This should be fixed in the latest release. Thank you for reporting!
Please do tell me if I've missed something :)

**Comment by OnkelTem** [comment]
It was really fixed, just updated! Thank you.
