### ISSUE TITLE
[FEATURE REQUEST] Go to Macro Config Window from Macro Home Window (Hotlink)

### ISSUE THREAD

**Issue by FelipeRearden** [chhoumann/quickadd#414]
Hello @chhoumann !!!!!!!

This is a simple FR related to **QoL** :)

I have almost 400 Macros Choices and many times during the year I have to change/modify my Macros due to new plugins and new core features from Obsidian. We are always improving :) 

This way, I really need a way to easily open the **Configure** window of a specific Macro Choice without having to look for the Macro inside the **Macro Manager** window 

📸 A button here 
![2BEB80A9-719D-46B0-8254-5D86D218CF92](https://user-images.githubusercontent.com/85180696/223759206-53f3075a-eea9-4692-981c-af99af41bce2.jpeg)

📸 To Access here 
![BBC7C63D-0034-4713-B921-68D4AE4D7033](https://user-images.githubusercontent.com/85180696/223759264-a1f1a687-82ed-4aa1-b98f-bf95e5f76340.jpeg)

---

Thanks for reading this !!!!! I hope you like my suggestion 🙏 🙏 🙏

Have a great day 🌞

**Comment by chhoumann** [comment]
Hey @FelipeRearden!

I think this would be a fantastic QoL upgrade, so I went ahead and added it.

Here are the new features:
![Obsidian_c1w5DpFn8W](https://user-images.githubusercontent.com/29108628/226095156-90cd7856-bc39-49c8-9a60-d42a47bf2027.gif)

Hope you find this implementation useful!

**Comment by FelipeRearden** [comment]
This is absolutely spectacular @chhoumann !!!!!!

It's much more smart than my FR, it's amazing how easy to edit AND create new MACRO from the home screen !!!!! 

I am gonna save so much time :)

Thank you very much @chhoumann  and **have a great day**  ☀️☀️☀️

**Comment by chhoumann** [comment]
Great to hear that! Thank you for checking it out. :)
