### ISSUE TITLE
Syntax error: unexpected identifier

### ISSUE THREAD

**Issue by clearf** [chhoumann/quickadd#417]
I am running Obsidian 1.1.16; QuickAdd 0.11.10 and, after upgrading (first to QuickAdd .08 and now to .10) I'm getting a syntax error when running a capture commend. 

![image](https://user-images.githubusercontent.com/1944486/223852855-419096e8-ddf0-4f79-a977-5daef6b43995.png)

I have not changed the existing capture commands, but they are now throwing an error.

If I create a new capture command that simply inserts something to the bottom of a file it works. 

Here's a command that doesn't work: 
![image](https://user-images.githubusercontent.com/1944486/223853187-f42ca825-f470-46cb-b9fa-fdd0496f8748.png)
![image](https://user-images.githubusercontent.com/1944486/223853207-eb92825a-39bf-4205-b229-662fa7aedfee.png)

Here's a very simple capture command that I just setup that is working: 

![image](https://user-images.githubusercontent.com/1944486/223853426-4d4c5434-2311-4dbd-8420-4b8eb880aafa.png)

What am I missing?

**Comment by clearf** [comment]
Update: I just deleted all my existing QuickAdd actions and added a new one trying to insert a formatted value into a file. I fails with the same error. 

![image](https://user-images.githubusercontent.com/1944486/224415249-ecc8d364-9310-4983-8a17-144bae810b3a.png)
![image](https://user-images.githubusercontent.com/1944486/224415281-5bc49e04-2226-47e2-936d-424eed5329fb.png)

The error appears to be thrown by onChooseCaptureType.run called on Line 16261 if that helps. 

```
  async onChooseCaptureType(captureChoice) {
    await new CaptureChoiceEngine(
      this.app,
      this.plugin,
      captureChoice,
      this
    ).run();
```

**Comment by chhoumann** [comment]
Hi @clearf 

Thanks for reporting this! I'm having trouble recreating the issue, so I'm wondering if it's some issue with the `data.json` file.
Can you try renaming the `data.json` in the QuickAdd plugin folder to `data_backup.json`? Don't want to delete it, but just force QuickAdd to create a new one.

Before renaming the file, please close Obsidian. It is fine to open again after renaming it.

The file will be located in your Obsidian vault, first in the `.obsidian` folder, then `plugins`, then `quickadd`, and finally there you'll find the file. So: `vaultFolder/.obsidian/plugins/quickadd/data.json`

Once you've opened Obsidian again, you won't have any of the QuickAdd settings. But please try creating a capture again and seeing if that works.

**Comment by clearf** [comment]
Hi @chhoumann,

I went back to try and reproduce, and I think I figured out the vexing problem via trial and error — there was a rogue Javascript file, loaded by another template (Templater) that somehow broke QuickAdd.

Obviously a strange corner case — right now I wonder if this is a documentation fix or better error messages rather than a technical fix.


Thanks, be well, and stay curious,
Chris Clearfield
MELTDOWN
***@***.******@***.***>
web<http://www.chrisclearfield.com/> | book<http://www.meltdownbook.net/> | linkedin<https://www.linkedin.com/in/chrisclearfield/> | the twitter<https://twitter.com/chrisclearfield>

p.s. Are you signed up for mailing list on leading with curiosity?  Sign up here<https://clearfieldgroup.ck.page/email> because I think you might enjoy it:  https://clearfieldgroup.ck.page/email


On Mon, Apr 03, 2023 at 4:50 AM, Christian Bager Bach Houmann ***@***.******@***.***>> wrote:

Hi @clearf<https://github.com/clearf>

Thanks for reporting this! I'm having trouble recreating the issue, so I'm wondering if it's some issue with the data.json file.
Can you try renaming the data.json in the QuickAdd plugin folder to data_backup.json? Don't want to delete it, but just force QuickAdd to create a new one.

Before renaming the file, please close Obsidian. It is fine to open again after renaming it.

The file will be located in your Obsidian vault, first in the .obsidian folder, then plugins, then quickadd, and finally there you'll find the file. So: vaultFolder/.obsidian/plugins/quickadd/data.json

Once you've opened Obsidian again, you won't have any of the QuickAdd settings. But please try creating a capture again and seeing if that works.

**Comment by chhoumann** [comment]
Now that you mention it, I actually recall this issue. It has been going on for a while, and is due to Templater not recognizing any script except those that follows a certain supported format.

Here's a fix for anyone seeing this issue in the future:
Templater needs its own specific scripts folder, or very odd errors will start appearing. My solution has been to create a `Templater` folder inside my `scripts` folder, i.e. `bins/scripts/templater`.

This should be set in the Templater settings, like so:
![image](https://user-images.githubusercontent.com/29108628/229600082-39677dd5-f1ef-4c2f-9866-9c6b7bd453c3.png)

Having this issue here should help anyone with this issue in the future.
Will update docs with a link here.

**Comment by clearf** [comment]
Thanks!
[??]


Thanks, be well, and stay curious,
Chris Clearfield
MELTDOWN
***@***.******@***.***>
web<http://www.chrisclearfield.com/> | book<http://www.meltdownbook.net/> | linkedin<https://www.linkedin.com/in/chrisclearfield/> | the twitter<https://twitter.com/chrisclearfield>

p.s. Are you signed up for mailing list on leading with curiosity?  Sign up here<https://clearfieldgroup.ck.page/email> because I think you might enjoy it:  https://clearfieldgroup.ck.page/email


On Mon, Apr 03, 2023 at 11:53 AM, Christian Bager Bach Houmann ***@***.******@***.***>> wrote:

Now that you mention it, I actually recall this issue. It has been going on for a while, and is due to Templater not recognizing any script except those that follows a certain supported format.

Here's a fix for anyone seeing this issue in the future:
Templater needs its own specific scripts folder, or very odd errors will start appearing. My solution has been to create a Templater folder inside my scripts folder, i.e. bins/scripts/templater.

This should be set in the Templater settings, like so:
[image]<https://user-images.githubusercontent.com/29108628/229600082-39677dd5-f1ef-4c2f-9866-9c6b7bd453c3.png>

Having this issue here should help anyone with this issue in the future.
Will update docs with a link here.
