### ISSUE TITLE
Typeerror [ERR_INVALID_ARG_TYPE] : data argument

### ISSUE THREAD

**Issue by davidszerman** [chhoumann/quickadd#42]
Hello,

I have just installed the plugin. I try to use it with a simple tempate and I have got the error 👍 
Quickadd : (error) TypeError [ERR_INVALID_ARG_TYPE]: the "data" argument must be of type string or an instance of buffer,...

Any idea of what I missed ?

Thanks

**Comment by chhoumann** [comment]
Hey! Thank you for your report. Could you provide me with some more information?

Which template are you using? Could you send it here?
What triggered the error?
What does the 'Choice' you made look like - your Template choice?
Can you show me an image of the error in the console?

**Comment by astratto** [comment]
I'm getting the same error.

I'm trying to use a simple template but I can reproduce it even with a basic text file with something plaintext like "Test" as content.

This is the simple configuration:

![image](https://user-images.githubusercontent.com/207754/125797566-bab2dc18-a695-4fdf-9100-298b6e7c5ae4.png)

Let me know if you want me to try anything in particular.

Obsidian v.0.12.10, QuickAdd 0.3.5

**Comment by chhoumann** [comment]
Hey @astratto, thank you for the details! That allowed me to figure it out. You need to write `.md` after the template name. That should fix it. :)

**Comment by astratto** [comment]
Thanks for getting back to me so quickly @chhoumann!

I tried, that still didn't work.
I've also tried upgrading, same problem.

I'd need to spend some time digging into the code.
Just in case it's something related to the path, my full path is `/Users/stefano/Library/Mobile Documents/iCloud~md~obsidian/Documents/Brain` <- notice the space between `Mobile` and `Documents`

**Comment by astratto** [comment]
Quite strange, it works fine now.
I had removed the plugin and started playing around locally with the git version so probably something got cleared between removing/installing the various versions.
Thanks!

**Comment by chhoumann** [comment]
That's quite odd. Well, I'm glad it works now. I was actually just about to dive in on this issue.

Thank you for your report, @astratto!
