### ISSUE TITLE
[FEATURE REQUEST] Wait for command

### ISSUE THREAD

**Issue by chhoumann** [chhoumann/quickadd#420]
Discussed in https://github.com/chhoumann/quickadd/discussions/419

**Comment by FelipeRearden** [comment]
Hello @chhoumann !!!!

I think this new FR is related to this one #118 that was created by me in the past :)

Maybe we are in the same page about a new Wait command. 

Have a great day ☀️

**Comment by chhoumann** [comment]
Hey @FelipeRearden!

Thanks for pointing that out, you're absolutely right! Great catch.

I'll close this one and use your original one as reference.

Thank you! And you too :)

**Comment by FelipeRearden** [comment]
> Thanks for pointing that out, you're absolutely right! Great catch.
> Thank you @chhoumann !!!! 
>
> I'll close this one and use your original one as reference.
> Okay !!! 
>
> Thank you! And you too :)
> :)
