### ISSUE TITLE
[BUG] Existing choice in the macro doesn't work

### ISSUE THREAD

**Issue by sarantsatsral-qy** [chhoumann/quickadd#433]
**Describe the bug**
I have an existing choice that I already added in the command ⚡ . This choice is under two multi-parents. Usually, I can add this kind of choice to a macro. But with the update, I think it has broken.

**To Reproduce**
1. Make a Multi/parent (multi B) choice inside another multi/parent choice (multi A).
2. Make a template choice inside multi/parent choice (multi B)
3. Add the choice to command ⚡ 
4. Create macro
5. Add existing choice.

```json
{
          "id": "b5144192-e686-410c-a765-30a04e831e38",
          "name": "🔻- 🗒💧 Note - AIC - Academic Journal, Thesis, Dissertation",
          "type": "Multi",
          "command": true,
          "choices": [
            {
              "id": "e98eeb5f-269c-437b-a65d-e05021e9dbcc",
              "name": "🗒 Academic Note",
              "type": "Template",
              "command": true,
              "templatePath": "03.00. Resources/03.00 Mini Template/B4.0. Academic Note 20211211105814.md",
              "fileNameFormat": {
                "enabled": true,
                "format": "{{VALUE:Author Last Name}}{{VALUE:Year}} - {{VALUE:Article Title}}"
              },
              "folder": {
                "enabled": true,
                "folders": [
                  "03.00. Resources/03.05. Journal Thesis Dissertation"
                ],
                "chooseWhenCreatingNote": false,
                "createInSameFolderAsActiveFile": false
              },
              "appendLink": false,
              "openFileInNewTab": {
                "enabled": true,
                "direction": "vertical",
                "focus": true
              },
              "openFile": true,
              "openFileInMode": "default",
              "setFileExistsBehavior": true,
              "fileExistsMode": "Increment the file name"
            },
```

**Expected behavior**
A choice that has been added to command (⚡) can be accessed through `add existing choice`

**Screenshots**
![image](https://user-images.githubusercontent.com/30141705/227810414-55c75f10-39b1-4b38-8a3a-e27b68453fe8.png)
![image](https://user-images.githubusercontent.com/30141705/227810430-b27ee256-296a-4df6-9175-321d1b85fe30.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Intel(R) Core(TM) i3-4150 CPU @ 3.50GHz 3.50 GHz RAM 12GB
 - Browser: Firefox
 - Version: 111.0.1

**Additional context**
Thank you, Chris! 🌻

**Comment by chhoumann** [comment]
Hey @sarantsatsral-qy 

Thanks for reporting this!
It was an oversight on my part. Should work now! :)

**Comment by sarantsatsral-qy** [comment]
Thanks @chhoumann for another fix you did for us. Have a very blessed life 😄

**Comment by chhoumann** [comment]
You as well, @sarantsatsral-qy :)
