### ISSUE TITLE
[BUG] Daily notes captured content going under the wrong heading

### ISSUE THREAD

**Issue by vnana-git** [chhoumann/quickadd#435]
**Describe the bug**
Capture content keeps going to the wrong heading in Daily notes (top of the 1st section heading), this issue only happen on daily notes, other folder and notes works fine

**To Reproduce**
The 3 screenshots below are using the same settings, except the file setting are different. And Only the daily turn on the default open after capture, the other two weren't.
<img width="882" alt="Settings" src="https://user-images.githubusercontent.com/28506374/229276117-92a1d86d-e38a-4eda-b856-fcda9739901b.png">

**Expected behavior**
Expected the content using the capture function would go under the heading was set in Quickadd.

**Screenshots**
Test cases videos:
[Today's daily note.mov](https://user-images.githubusercontent.com/28506374/229276710-1bd6b67c-6a0f-4962-8b5f-3a3ea1eb83eb.mov)
[Input Manual Date (To add content under the input date).mov](https://user-images.githubusercontent.com/28506374/229276718-715016b6-01d5-4d26-9ea9-dc13be8727d0.mov)
[Other pages test.mov](https://user-images.githubusercontent.com/28506374/229276773-239ac766-0128-432a-8c89-0746e1c48139.mov)

**Desktop (please complete the following information):**
 - OS: iMac Intel
 - Version Ventura 13.0.1

**Comment by chhoumann** [comment]
Hey @vnana-git, thanks for reporting this!

I've made an attempted fix based on the details you've submitted.
Can you check if it works in the v0.18.0 release?
