### ISSUE TITLE
[BUG] Capture to active file doesn't honor cursor location

### ISSUE THREAD

**Issue by Siirraa** [chhoumann/quickadd#439]
**Describe the bug**
Since version 0.18.0 a simple capture text appears on the top of the file instead of where the cursor is when the hotkey is pressed

**To Reproduce**
1. Create a simple capture entry
2. Set it to "Active file"
3. Set the capture format
4. Insert something with 2 lines (in my case) text

**Expected behavior**
The text should be inserted where the cursor is like it always did

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**
I reverted back to 0.17.1 when I noticed this issue and there it works fine.

**Comment by chhoumann** [comment]
Hi @Siirraa, thank you for reporting this!

 I've just pushed an update which should fix the issue. Should be 0.18.2.
Can you confirm this on your end? Apologize for the inconvenience this may have caused!

**Comment by Siirraa** [comment]
I just updated and tested and I can confirm it works as expected once again.

Many thanks for your great work, I'm using QuickAdd all day, every day.
