### ISSUE TITLE
[BUG] Templater not rendering for inserts into active file

### ISSUE THREAD

**Issue by zerowidth** [chhoumann/quickadd#440]
**Describe the bug**

While #439 and #196 were fixed in 0.18.2, templater syntax is no longer rendering/being replaced.

**To Reproduce**
1. Configure an insert test:

<img width="539" alt="image" src="https://user-images.githubusercontent.com/3999/229937610-01006906-f500-4050-a057-00c3220f9a9d.png">

2. Create a test document, position cursor in middle line:

<img width="266" alt="Screenshot 2023-04-04 at 4 37 57 PM" src="https://user-images.githubusercontent.com/3999/229937701-0f244790-a611-4e2e-89e7-934e590a42f4.png">

3. Use the insert test:

<img width="266" alt="image" src="https://user-images.githubusercontent.com/3999/229937769-e5d5f296-ca51-4ae7-8827-ee377f755e85.png">

**Expected behavior**

Templater syntax replaced.

**Screenshots**

Above.

**Desktop (please complete the following information):**
 - OS: macos
 - Browser: safari (n/a?)
 - Version: 1.18.2

**Comment by zerowidth** [comment]
I tested templater syntax in a quickadd that uses a template and that still works.

**Comment by zerowidth** [comment]
Rereading docs, I didn't see any explicit mention that `<% tp... %>` syntax would work in the first place, despite it having worked previously.

I tested the above behavior by extracting the `<% tp.date.now() %>` into a template file and using `{{TEMPLATE:...}}`, and got the same result: un-replaced/rendered templater syntax.

**Comment by chhoumann** [comment]
Hi @zerowidth! Thank you for reporting this.

I had mistakenly left out the Templater parse command when adding the previous features.
It should be working in 0.18.3 again, as per my tests. Can you confirm this on your end?

Also, quick question if you don't mind:
Which Templater features do you use that QuickAdd doesn't support (or doesn't support adequately)?

**Comment by zerowidth** [comment]
Confirmed as fixed, thank you!

---

Given the overlap between quickadd and templater, I'm sure there's ways I can accomplish the same thing in either, but here's the general set of features I'm using:

1. Binding a hotkey to a templater for quick insertion of a snippet

It looks like as long as I have a command enabled for a quickadd capture, I can also bind a hotkey, so there's direct feature parity here.

2. Simple setup for user functions that execute external scripts in templater, which I use in a variety of ways.

Since I work with GitHub issues a lot, I like to insert rich markdown links into my daily notes. I use a [github CLI](https://cli.github.com) extension I wrote for this, https://github.com/zerowidth/gh-md. In templater, I configure the `markdownLink` system command as `PATH=$PATH:/opt/homebrew/bin /opt/homebrew/bin/gh md link "$input"` and invoke it in captures. For example, my "review PR" capture is `review <% tp.user.markdownLink({input: (await tp.system.clipboard())}) %>` formatted as a task.

I expect I can set these up as macros too, but it wasn't obvious how to wire up a shell command in quickadd.

3. using `await tp.file.rename` to (re)set the name of a new file based on the clipboard contents

I've got a more complex capture/template that creates a "project" document for a GitHub issue. Part of this is naming the file. I've got the `markdownTitle` system command in templater as `PATH=$PATH:/opt/homebrew/bin /opt/homebrew/bin/gh md  title --sanitize "$input"`, and use this in the issue project template with `<%- await tp.file.rename("Issue - " + tp.date.now("YYYY-MM") + " - " + (await tp.user.markdownTitle({input: (await tp.system.clipboard())}))) -%>`

If I could use the system commands easily in a quickadd macro, could I skip the rename step by including a `{{MACRO:}}` call in a file capture filename?

---

All that to say: there aren't any particular reasons I'm using templater versus quickadd beyond a desire to get obsidian to do the things I want as easily as possible, and it wasn't obvious how to configure macros versus the configs for running shell commands in templater.

Thanks!

**Comment by FelipeRearden** [comment]
> Also, quick question if you don't mind: Which Templater features do you use that QuickAdd doesn't support (or doesn't support adequately)?

Sorry for step into this conversation. I know that looks a tiny thing, but it really bothers me is that the `suggester prompt ` and `{{VALUE:}}` returns `undefined` if the user inputs nothing (empty).

On the other hand, in Templater, when the user input in empty, it inserts nothing which I think is the best option. 

This is the FR related to this issue → #209  🙏

**Comment by FelipeRearden** [comment]
> And thank you, @FelipeRearden! I think it would make a lot of sense to overhaul that. I've made #448, so I can go through each format syntax element and make better defaults when no input is given.

Thank you very much for this @chhoumann !!! 

I am glad that you liked my suggestion. It's a detail that will help in many workflows 😀 

Have a great day!!!!!!
