### ISSUE TITLE
[BUG]-[MOBILE] yesNoPrompt → Keyboard Navigation between Buttons YES - NO

### ISSUE THREAD

**Issue by FelipeRearden** [chhoumann/quickadd#444]
**Describe the bug**

Hello @chhoumann !!!

🆘 This Issue only Happens on Obsidian Mobile on version 0.19.2

I am struggling to using the keyboard when I am navigation in a `yesNoPrompt`

I saw that when I use <kbd>TAB</kbd> OR <kbd>SHIFT+TAB</kbd> I CAN go from `YES` to `NO` but I CANT go back to `YES` from `NO`

I have a screenshot below to explain :)

**To Reproduce**
1. Open a `yesNoPrompt`
2. Use <kbd>TAB</kbd> to change the focus on button
3. `NO` is focused
4. Use <kbd>TAB</kbd>  or <kbd>SHIFT+TAB</kbd> to change the focus on button `YES`
5. The focus keeps on `NO` button 

Start Another Round 

1. Open a `yesNoPrompt`
2. Use <kbd>SHIFT+TAB</kbd> to change the focus on button
3. `NO` is focused
4. Use <kbd>TAB</kbd>  or <kbd>SHIFT+TAB</kbd> to change the focus on button `YES`
5. The focus keeps on `NO` button 

**Expected behavior**
Be able to switch between YES and NO with the keyboard 

**Screenshots**

I am using this snippet to emphasize the focus ...

```css
.modal-container.quickAddModal.qaYesNoPrompt.mod-dim .modal .modal-content .yesNoPromptButtonContainer button:focus {
	border: 5px solid blue;
}
```

![video](https://user-images.githubusercontent.com/85180696/230130687-8b4caa5d-61b6-4864-a27a-dd2eaab796d5.MOV)

**Smartphone (please complete the following information):**
 - Device: iPadPro
 - OS: iPadOS 16.2
 - Browser Safari
 - Version I dont know :(

**Additional context**

If possible 🙏 would be amazing if we could navigate in the `yesNoPrompt` using the **arrow keys** <kbd>→</kbd> and <kbd>←</kbd>  additional to <kbd>SHIFT+TAB</kbd> and <kbd>TAB</kbd>

ℹ️ Let me know if I can open an FR for this new feature. 

---

Thanks for reading this !!!!!

**Comment by chhoumann** [comment]
Hey @FelipeRearden! Thank you very much for reporting this.

Unfortunately, I cannot recreate this issue completely.
Shift-tab gets stuck on `No` for me, but not tab.

Wondering if this is a mobile thing. I even tried using the Obsidian mobile emulator.
Might need to test on a mobile device with a physical keyboard. Will see what I can do about that.

In the meantime, I've gone ahead and added arrow key navigation to the `yesNoPrompt`.
The feature is on the `dev` branch, and will be released with the next batch of updates :)

**Comment by FelipeRearden** [comment]
> Wondering if this is a mobile thing. I even tried using the Obsidian mobile emulator.
> 
> Might need to test on a mobile device with a physical keyboard. Will see what I can do about that.

Hello @chhoumann !!!!

Thank you very much for the reply :)

Unfortunately, mobile emulator fails to recognize issues on modals related to keyboard navigation. I have some problems with native features as well. 

> In the meantime, I've gone ahead and added arrow key navigation to the `yesNoPrompt`.

I think is the best idea @chhoumann !!! My suggestion is to not bother with this issue since the arrow keys is much more intuitive 😀 

> The feature is on the `dev` branch, and will be released with the next batch of updates :)

Amazing, thank you very much. When we have a new update, I test this feature and get back to you 😀 

thanks again @chhoumann !!!! Have a great day ☀️

**Comment by chhoumann** [comment]
Hey @FelipeRearden!

The update was just released.
I'll consider the arrow keys workaround a fix for this issue. :)

Thank you for your thoughts!
Have a great day :)

**Comment by FelipeRearden** [comment]
Hello @chhoumann !!!!

> The update was just released.
> 
> I'll consider the arrow keys workaround a fix for this issue. :)

Arrow keys Working perfect on version 0.2.0 on Obsidian Mobile on iPadOS !!!!

Thank you very much for this fix/feature 😀 

Have a great day ☀️
