### ISSUE TITLE
[BUG] Capture to Active File Captures Only to Cursor Position 

### ISSUE THREAD

**Issue by julroger2013** [chhoumann/quickadd#445]
**Describe the bug**

I am trying to use QuickAdd to capture to a particular section of my active note—a heading titled: ## Delivered

For whatever reason, the material designated for capture instead goes to wherever my cursor is currently located, rather than to the bottom of the "## Delivered" section of my note. 

An example of my settings for this QuickAdd choice is in the below screenshot. The desired section exists within the note, so the fact that option is toggled off shouldn't make a difference.

**Screenshots**

![image](https://user-images.githubusercontent.com/94991208/230150283-398b4b22-b6d3-40a8-bf92-99f15928f965.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Obsidian v. 1.2.2 (Insider)

**Comment by chhoumann** [comment]
Hi @julroger2013, thanks for reporting this! Seems I omitted checking if Insert After was enabled. Should be fixed in the latest release - 0.19.3. Can you confirm this on your end?
