### ISSUE TITLE
[BUG] (Mobile, Android) Capture UI cannot be closed by tapping on "x", and Capture Format field is almost completely hidden

### ISSUE THREAD

**Issue by the0s0ph1st** [chhoumann/quickadd#446]
**Describe the bug**
Exactly what's on the title.

**To Reproduce**
1. Open QuickAdd, create a Capture or add a Capture step in a macro.
2. Open the Capture action to edit it.
3. The "Capture Format" text field is almost completely hidden by the bottom margin, there is still some area where I can tap and type, but what I am typing is almost completely obscured.
4. Tapping the "x" on the upper right does not close the Capture UI.

**Expected behavior**
For step 3, I expected the Capture Format field to be fully visible.
For step 4, I expected for the Capture UI to close upon tapping on "x"

**Screenshots**
https://user-images.githubusercontent.com/40872841/230280108-7a9255f9-afc6-4590-942c-c6d1b4c0be86.mp4

**Desktop (please complete the following information):**
 - not tested

**Smartphone (please complete the following information):**
 - Device: OnePlus 7T
 - OS: Android 12
 - Obsidian App Version 1.4.3

**Additional context**
I noticed the problem only after the last update of Android weeks ago. I am using the Minimal theme (also updated it) but even using the default theme does not correct it, nor does turning off any or all of the community plug-ins.

**Comment by the0s0ph1st** [comment]
Update: 
I had thought that the problem was just want connected to the theme, so I tried uninstalling then installing the app, then making a new test vault. 

The problem was still there.

![Screenshot_2023-04-07-09-33-31-89_51606159b24eff83e24a54116878fe3e](https://user-images.githubusercontent.com/40872841/230644589-8f409624-ae6b-4fc3-aba6-4f0e0540e757.jpg)

So I was right that it could have been affected by the new Android OS

**Comment by the0s0ph1st** [comment]
Never mind I just bought a new phone it needed to be replaced anyways.

**Comment by chhoumann** [comment]
Hey @the0s0ph1st, thanks for reporting this! 

Seems to also be pretty poor looking on my iPhone, so I'm reopening & fixing this asap.

Emulator:
![image](https://user-images.githubusercontent.com/29108628/230959878-ce37be8a-f466-4190-bfbf-f00c7471e9bd.png)

**Comment by chhoumann** [comment]
Just pushed a fix for this that sets the minimum size of the capture format field. :)
