### ISSUE TITLE
cancelling a template add brings up an error

### ISSUE THREAD

**Issue by firinael** [chhoumann/quickadd#45]
Hi, just started trying out the plugin, and ran into a curious behaviour.

Whenever I press ESC after selecting a template to add, I get this error:

![image](https://user-images.githubusercontent.com/67032657/124338512-c9076780-db7e-11eb-9132-8cbbf6ac2ed6.png)

And this only happens with the `add template` function, as far as I've noticed.

**Comment by chhoumann** [comment]
Thank you! Fixed in the latest version. :)
