### ISSUE TITLE
[BUG] Capture to arbitrary file throws "file not found" error

### ISSUE THREAD

**Issue by lyndhurst** [chhoumann/quickadd#454]
**Describe the bug**
I want to insert a link to the current file to another note of my choice. Leaving the "capture to filename" field empty or setting it to `/` as recommended in the documentation throws a "file not found" error.

**To Reproduce**
1. Create a new test vault with at least two notes: "Note A" and "Note B"
2. Install and enable quickadd
3. Go to quickadd settings and create a capture
4. Leave everything default but the "capture format" that should be set to {{linkcurrent}}
5. Open "Note A" and launch the capture
6. Select "Note B" in the suggester
7. An error should be thrown  

**Expected behavior**
A wiki link to "Note A" should be inserted into "Note B".

**Screenshots**
Not easy for me to add screenshots now; I will if needed.

**Desktop (please complete the following information):**
 - OS: Tried on both Ubuntu 18.04, and an up to date manjaro 
 - Both have Obsidian 1.1.16 installed (first from flatpak, second from the AUR)
 - Plugin version: 0.19.4

**Additional context**
- Please note that the bug happens when leaving the "filename" field empty OR setting it to `/`.
- Setting the "filename" field to "Note B" works as expected (a link to "Note A" is inserted into "Note B").
- I tested in a fresh vault with a fresh obsidian install with a couple of notes only, and my personal vault with hundreds of notes and a dozen folders. The behavior is the same even setting the "filename" field to one of those folders.
- This is the first time I install and use QuickAdd, so I have not tried any other functionalities.

I hope I am not doing something wrong; thank you for your time.

**Comment by chhoumann** [comment]
Hi @lyndhurst, thank you very much for reporting this & with so many details. It really helped me nail down the issue.

I've just implemented what I believe to be a fix. It'll get released in the next update. Can you confirm that it works now? :)

**Comment by lyndhurst** [comment]
Hi @chhoumann I have just tested it quickly, and, yes, it works as expected now.

Thank you for fixing it !

**Comment by chhoumann** [comment]
Great! Thanks for testing.
