### ISSUE TITLE
[FEATURE REQUEST] Suggested improvements to capture

### ISSUE THREAD

**Issue by davecahill** [chhoumann/quickadd#46]
**Observed behavior**
I set up a capture workflow based on the daily notes template, but I specified the daily notes template incorrectly - a template name which didn't exist due to incorrect capitalization.

I was able to launch the workflow, but it failed silently (no input box shown), so I was confused.

I looked in the console in developer tools and saw that logs were complaining about template file not found, and was then able to fix.

**Describe the solution you'd like**
I think the ideal solution would be to have template file name autocomplete / predict in the "template file" input field, but maybe that's not possible in the settings pane?

Alternatively, I think displaying an error to the user would be useful, to avoid the need to dig in to the developer tools console.

**Additional context**
QuickAdd 0.2.15
Obisidian v0.12.9 (insider build)
MacOS Big Sur 11.4

**Comment by chhoumann** [comment]
Hey! Thank you very much for your feature request.

Just for my own clarity, are you referring to this input field? Because it should already provide suggestions.
![image](https://user-images.githubusercontent.com/29108628/124358847-71bad300-dc22-11eb-9e5a-87d6715f0b1b.png)

If not, I imagine you are referring to the `Capture To > File Name` field, where mine says (in the picture): `personal/inbox/tasks.md`?

**Comment by davecahill** [comment]
Thanks for the quick reply!

Yes, I was referring to the "Create file with given template" field. I don't see autocomplete on it, and I'm on the latest version of QuickAdd I think (1.7.1).

It's possible I'm doing something wrong of course, so here's a short capture of me trying out autocomplete on that field, in case it helps:
![quickadd](https://user-images.githubusercontent.com/361096/124370892-f9522180-dcb6-11eb-8f53-c7da9884824e.gif)

**Comment by chhoumann** [comment]
Thank you for the details!

Just to make sure, could you install QuickAdd from the community plugin store? I just released 0.3.3 yesterday - and I can't remember which version I added autosuggestions in haha.

You don't need to remove QuickAdd first, it'll just be overwritten.

I'd recommend (in any case) to back up the data.json file in the QuickAdd plugin folder.
It's in your Obsidian vault folder > .obsidian > quickadd.

**Comment by davecahill** [comment]
I mentioned the version of the Advanced URI plugin above (1.7.1) by accident - my version of QuickAdd was already 0.3.3. I backed up the data.json, uninstalled, reinstalled, reinstated data.json. Confirmed that on my machine, the template filed doesn't autocomplete.

**Comment by chhoumann** [comment]
Great! Do you use the core templates plugin? Or Templater? Or both?

Have you set your templates path in these plugins?
If so, could you send them?

Does the console say anything when you write in that input field? Or are there any other errors?

Console guide:
To check for errors, first open the developer tools by pressing `Ctrl-Shift-I` on Windows/Linux or `Cmd-Opt-I` on macOS, and then go to the "Console" tab.

**Comment by davecahill** [comment]
Apologies for the delay here - I wasn't using either of those plugins.

I was just using the Daily Notes feature, and I had a template set up in that for my daily notes.

So when I set up the capture workflow, I just wanted to refer to that daily notes template.

No errors in console. Hope that helps!

**Comment by chhoumann** [comment]
Thank you, @davecahill! That does explain things. I've set it up with the assumption that users use either Templater or Templates (or both), and the suggester will fetch templates from the folders specified in the settings for those plugins.

I'll make the 'failing' more explicit.
