### ISSUE TITLE
[BUG] {{time}} doesn't render when triggering a template

### ISSUE THREAD

**Issue by henryfaber** [chhoumann/quickadd#464]
I have an Obsidian template with {{date}} and {{time}} in the frontmatter. 

When I trigger a _QuickAction Template_, {{date}} renders the expected current date, but {{time}} is ignored and outputs as {{time}}. This happen within the body of the note, as well.

Inserting the Obsidian template without the use of the QuickAction plugin renders {{time}} with the current time, as expected.

Expected behaviour: when triggering a QuckAdd Template, {{time}} renders the current time in the default format specified in Obsidian.

- M1 iMac
- MacOS 13.2.1
- Obsidian v1.2.3
- QuickAdd 0.21.0

Thank you!

**Comment by chhoumann** [comment]
Hi @henryfaber 

Thanks for opening the issue.
This isn't actually a bug: https://github.com/chhoumann/quickadd/issues/364

But I'm getting enough of these to warrant just adding the feature.
Will be in 0.22 :)

Please let me know if it works as expected.

**Comment by henryfaber** [comment]
Wow, that was fast! I didn't realize you were custom re-rendering the tags in the Obsidian template format - I wouldn't have bugged you if I knew that, but it makes sense since you have so much control with {{DATE:}} in the settings.

{{time}} default you've set is 24hrs which works, but I can see how someone may want that extra control in the future. All of that being said, fantastic work and thank you for being so responsive!

**Comment by chhoumann** [comment]
No worries! I think it should have been added much earlier, if nothing else then simply to have carryover and a more flowing experience when learning templates in Obsidian. 

Thank you! Sure thing :)
