### ISSUE TITLE
[BUG] 'Create file if does not exist' not working when using 'Capture to Tag'

### ISSUE THREAD

**Issue by lyndhurst** [chhoumann/quickadd#477]
**Describe the bug**
When using the 'Capture to Tag' feature while simultaneously enabling the 'Create file if does not exist' setting in the capture dialog, I cannot create a new file by entering a file name not listed in the suggester. 

**To Reproduce**
1. Create a new capture,
2. Set the filename field to a tag existing in your vault
3. Enable 'Create file if does not exist' option
4. Launch the capture
5. Type a file name not present in the suggester
6. The 'Result not found' message appears under the text box
7. Try hitting `<Enter>` , nothing happens

**Expected behavior**
The non existing filename you typed in the suggester should appear in bold with no error message, and hitting `<Enter>` should create a file named accordingly.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Obsidian: 1.1.16
 - QuickAdd 0.21.0

**Additional context**
- Simply removing the tag in the 'Filename' text field from the capture settings dialog makes the file creation feature of the capture work as expected.
- I wondered if this was the normal behavior for 'Capture to tags' but did not find any mention of it in the doc.
- I did not test the 'Capture to folder' behavior.

Hope you got all you need, thanks for all your efforts to maintain this very useful plugin :+1:

**Comment by chhoumann** [comment]
Hey @lyndhurst, thanks for reporting this! I had used the wrong suggester in the implementation. 
I just pushed a fix to the dev branch. You'll get a comment here when the fix is included in a release.
Then please tell me if it's working as expected :)

**Comment by lyndhurst** [comment]
I could only do a quick test this morning, but it seems to be fixed. I got the "capture to tag" feature to create a file based on the template specified. Thank you @chhoumann , and have a great WE :+1:
