### ISSUE TITLE
[FEATURE REQUEST] "Do not send my notes to ChatGPT (or other external providers) no matter what" switch

### ISSUE THREAD

**Issue by AdamNorberg** [chhoumann/quickadd#478]
### Is your feature request related to a problem? Please describe.

QuickAdd release 0.23.0 adds ChatGPT features. I absolutely, 100%, completely, cannot allow my work notes to be sent to an external service provider. [ChatGPT has already been the focus of headlines about folks being incautious with confidential information](https://gizmodo.com/chatgpt-ai-samsung-employees-leak-data-1850307376) and I need more confidence that QuickAdd will never _automatically_ enable this or any feature like it.

For now, the API key requirement makes it hard to activate accidentally, but there is no unambiguous "do not enable this feature" switch (ideally defaulting to "do not do the thing") anywhere in the UI. I don't feel confident that my decision not to provide an API key will be correctly understood as "absolutely do not do this ever".

### Describe the solution you'd like

I would like a clear toggle switch on the main QuickAdd settings page to enable or disable AI assistance features. Future QuickAdd releases would need to interpret this switch as "do not do the thing" rather than "oh, the user did not configure the thing, now we can configure the thing for them so let's do that".

There's nothing special about "AI assistance features" in this regard -- _any_ integration of an external service into a formerly local-only plugin needs a very clear unambiguous kill switch, ideally set to "do not do the thing" by default and definitely not silently reconfigured or ignored by plugin updates.

### Additional context

Although ChatGPT specifically [has leaked user content in the past](https://www.malwarebytes.com/blog/news/2023/03/chatgpt-reveals-chat-history-of-other-users), this is a problem with _any_ unapproved external service regardless of whether they have had known information leaks or not. People who use Obsidian as part of their day job typically have confidentiality obligations to their employer.  A local-only plugin suddenly adopting external service connections I have been going out of my way to avoid is an unwelcome surprise -- I definitely see how it's useful to all sorts of folks, but it's just not an appropriate thing for me to do with the notes in my vault.

**Comment by chhoumann** [comment]
Hi @AdamNorberg 

Thank you for raising this issue.

I want you, and everyone else, to feel safe using QuickAdd.
For this reason, I've added a setting to disable AI features - and online features, for future-proofing the promise of not contacting external providers.

Do note that you can still execute arbitrary code in user scripts and therefore contact external services - but that would be code that you (the user) write or place in your vault manually.

Adding the AI Assistant enables those that want it to use it to leverage AI in their vault. As you mention, the AI Assistant won't work without an API key currently. And now, it won't work if the new setting is enabled, either.

![image](https://github.com/chhoumann/quickadd/assets/29108628/05ea3342-5531-49f8-b41d-a5a26cda18be)

The setting will, of course, be considered and honored in future iterations of QuickAdd. 

I also have confidential data that I wouldn't want to send to external services, ever. Ownership & privacy is one of the reasons I started using Obsidian. 

I hope to make it clear that I intend QuickAdd to always honor your privacy & data, giving you full control of how, when, and for what it's used.
Adding this feature is hopefully a sign of that.

If you, or anyone else, has any further concerns, then please let me know.
I'd be happy to address them.

**Comment by AdamNorberg** [comment]
Thank you for your prompt implementation, this is exactly what I was looking for!
