### ISSUE TITLE
[BUG] No command selected for macro in newer version.

### ISSUE THREAD

**Issue by Lennart-Lucas** [chhoumann/quickadd#480]
I'm currently seting up a new vault and have some issues creating macros.
For the setup I'm using the same macro setup as I have in an older vault where it works fine.
The setup seems to go fine, but when I execute it using the command pallet it gives an error indicating that it wasn't configured properly.

Reproduction:
1. First I set up the configuration of the macro itself. It just contains a simple capture. 
![Screenshot 2023-04-30 122423](https://user-images.githubusercontent.com/37398342/235348357-16fc2c52-9c64-49b3-a7fd-0b65c4d8f2e4.png)
![Screenshot 2023-04-30 122530](https://user-images.githubusercontent.com/37398342/235348394-6cca02fb-bf12-4a31-99f1-8aa6fc413255.png)
2. After that I create the macro for the command, select the macro configuration I made and create a command for using the little lightning bolt button
![Screenshot 2023-04-30 122902](https://user-images.githubusercontent.com/37398342/235348432-91f5a36a-13a8-4f9a-932e-120407a65ae8.png)
3. I think this would configure the macro correctly, but when I run it, it mentions that the macro has no commands.
![Screenshot 2023-04-30 122934](https://user-images.githubusercontent.com/37398342/235348462-09f91eb2-b5f8-4cdc-9177-90a6e4f3e987.png)
![Screenshot 2023-04-30 122949](https://user-images.githubusercontent.com/37398342/235348463-bc223665-b8c1-4fc5-816f-67a7f123b4d7.png)

I might be missing something simple, in which case I appologize, but there seems to be something broken.
My new vault has quickadd 0.23.0 while my old one has version 0.11.9.

**Comment by chhoumann** [comment]
Hey @Lennart-Lucas, thanks for reporting this!

I've just pushed a fix to the dev branch. When it's included in the next version, you'll get a message here.
Please let me know if it works for you!
