### ISSUE TITLE
[BUG] Unable to provide Zotero API key for Zotero Importer

### ISSUE THREAD

**Issue by lpdoherty22** [chhoumann/quickadd#482]
No longer able to provide Zotero API key or user details when configuring QuickAdd macro

1. Manage macros
2. Add macro then go to configure it
3. Add user script, Zotero Import Script (quickadd.js)

Here I have been able to click setting in the past and add my Zotero credentials. I am unable to do this now. I can not acess this dialogue from your great [blogpost](https://bagerbach.com/blog/how-i-read-research-papers-with-obsidian-and-zotero) as before.
![image](https://user-images.githubusercontent.com/47311193/235678187-8c1b1773-2f92-4f66-8fc3-5a4a768c18f6.png)

Using QuickAdd version 0.23.0 and had previously been working well with this version.

**Comment by chhoumann** [comment]
Hey @lpdoherty22, did this start working since you closed the issue?

**Comment by lpdoherty22** [comment]
Hi Christian,

Thanks for your email. Yes it ended up resolved though I have no idea how.
May have had something to do with the most recent obsidian update as it
resolved after that had installed.

Thanks again, quickadd is a really clever plugin, super flexible. Just
trying to get the hang of <variables>

Thanks,

Leo

**Comment by chhoumann** [comment]
I'm glad to hear that it got resolved.

Let me know if you need assistance with variables. You can always open a [discussion](https://github.com/chhoumann/quickadd/discussions) if you need help.

Otherwise, the [docs](https://quickadd.obsidian.guide) are also here to help.

Thank you & and best regards,
Christian
