### ISSUE TITLE
[BUG] Unexpected error message

### ISSUE THREAD

**Issue by Smitty010** [chhoumann/quickadd#487]
**Describe the bug**
I have a QuickAdd capture with the following capture format: `> [!my-comment] {{VALUE: Your comment}} (w/o backticks)`.  When I run it I get a message "QuickAdd: (ERROR) TemplaterError: Invalid reference date format, try specifying one with the argument 'reference_format'".  I'm not sure what the problem is.  There's no date reference.

**To Reproduce**
Just create a capture with the specified Capture format.

**Expected behavior**
I expected it to generate a callout with the type "my-comment" and the "Your Comment" filled in with the prompt input

**Screenshots**
![image](https://user-images.githubusercontent.com/3760075/236931301-8a341633-1e17-4fc9-9201-6d3244b22dcc.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 11
 - Browser [e.g. chrome, safari]: Chrome
 - Version [e.g. 22] latest windows 11
- Obsidian: 1.2.8
- QuickAdd: 0.23.0

**Smartphone (please complete the following information):**

**Additional context**
I thought this used to work

**Comment by chhoumann** [comment]
Hey @Smitty010, thanks for reporting this!

This seems to work on my end.

Just a hunch, but if you disable Templater, does it work then?

Do you have any Templater stuff in the file you're capturing to?

**Comment by Smitty010** [comment]
I can't remember which file i was doing this in when I got the error.  However, when I tried it this morning on a different file, it worked fine.  I'll assume it was some funny interaction between quick add and some templater stuff in that file.  If I can consistently reproduce it, i'll come back.  Closing for now.

**Comment by chhoumann** [comment]
Thanks!

**Comment by Smitty010** [comment]
Thank you
