### ISSUE TITLE
[BUG] User Script don't work on Obsidian for Android

### ISSUE THREAD

**Issue by mpco** [chhoumann/quickadd#50]
**Describe the bug**

I found that quickadd's user script does not work on Obsidian for Android. After debugging I got the error message: 
`Uncaught TypeError: this.app.vault.adapter.getBasePath is not a function`

**Smartphone:**
 - OS: Android 11
 - Obsidian: 1.0.3
 - Version: 0.3.9

**Comment by chhoumann** [comment]
Hey @mpco!
I've made a fix that, from my tests, make scripts work on mobile as they do on desktop. I'll push the fix in the next update.
