### ISSUE TITLE
[FEATURE REQUEST] allow descriptions in fields

### ISSUE THREAD

**Issue by danielo515** [chhoumann/quickadd#544]
**Is your feature request related to a problem? Please describe.**
Configurable scripts are great. However they lack a key feature: descriptions.
Using someone script where all you can see is the author, title and field names is not going to help you understanding how to use it.

**Describe the solution you'd like**
I think that allowing to define descriptions for both the script and each field will make it easier for people to understand how configuration is supposed to be setup and how the script is supposed to be used.

**Additional context**
This is specially handy in case you have scripts that "set variables". Descriptions could explain what variables will be set and with wich name so you can use them easier in complex macros

**Comment by FeralFlora** [comment]
I came here to request the same thing, since I am developing a Quickadd script for dissemination to others 

Without a description, the setting/field names have to be longer and / or you have to provide a lot more instructions to go along with the script. 

Descriptions would make user scripts a lot more self-explanatory.

**Comment by danielo515** [comment]
As a workaround (a bit overkill one) I've built a new plugin: https://github.com/danielo515/obsidian-modal-form
It is designed to integrate nicely with other plugins like quickadd

**Comment by FeralFlora** [comment]
> As a workaround (a bit overkill one) I've built a new plugin: https://github.com/danielo515/obsidian-modal-form It is designed to integrate nicely with other plugins like quickadd

That's very cool! Does it also work with Quickadd's user script settings?

**Comment by danielo515** [comment]
> > As a workaround (a bit overkill one) I've built a new plugin: https://github.com/danielo515/obsidian-modal-form It is designed to integrate nicely with other plugins like quickadd
> 
> That's very cool! Does it also work with Quickadd's user script settings?

Not sure what do you mean by that, could you elaborate?
It works in every place you can access the global `app` object

**Comment by FeralFlora** [comment]
@danielo515 I've made a user script for Quickadd with settings that you can specify. Quickadd provides this settings page:
![Obsidian_k60623WeiF](https://github.com/chhoumann/quickadd/assets/33608083/9a9ebbe6-9801-40ba-bee2-888fe8ecfe3a)

Can your plugin override that and add descriptions?

**Comment by chhoumann** [comment]
Great feature request. In hindsight, it should have been there from the beginning! Thank you.

I just added it in the latest release :)

**Comment by FeralFlora** [comment]
@chhoumann Nice! I assume that it's just `description: "Description text"`?

**Comment by chhoumann** [comment]
> @chhoumann Nice! I assume that it's just `description: "Description text"`?

Yep!

**Comment by danielo515** [comment]
> @danielo515 I've made a user script for Quickadd with settings that you can specify. Quickadd provides this settings page: ![image](https://user-images.githubusercontent.com/33608083/271211417-2f94f992-935b-4381-8063-8371ae36c88b.png)
> 
> Can your plugin override that and add descriptions?

Oh, I see. No the integration is not that deep 🙂

**Comment by FeralFlora** [comment]
> Oh, I see. No the integration is not that deep 🙂
Okay, well doesn't matter now that the feature request has been implemented 👍
