### ISSUE TITLE
[FEATURE REQUEST] "Create line if not found" at Top inserted AFTER frontmatter

### ISSUE THREAD

**Issue by n-konig** [chhoumann/quickadd#545]
# Description
When using "Insert after" -> "Create line if not found" with setting "Top", the line created displaces the frontmatter (as it really does create the line at the very top of the file!)

# Suggestion
Could the "Create line if not found" ignore the fronmatter, so that creating the line at the "Top" actually creates the line after the frontmatter is closed? This would be brilliant!

# Additional context
For example

```
---
key: value
---
```

now becomes

```
# Line created at the Top
---
key: value
---
```

but would preferably become

```
---
key: value
---
# Line created at the Top
```

Regards,
Niclas

**Comment by f3d3r1c098** [comment]
is this issue back on version 1.8.1?
