### ISSUE TITLE
[BUG] Newlines are inserted between tasks when using Capture choice

### ISSUE THREAD

**Issue by ericaxu** [chhoumann/quickadd#55]
**Describe the bug**
Newlines are inserted between tasks when using Capture choice

**To Reproduce**
1. Go to QuickAdd settings;
2. Create new Capture choice;
3. Select existing Markdown file;
4. Tick "Task" toggle to format it as task;
5. Tick "Write to bottom of file";
6. Trigger this choice, enter "test", and then press Enter;
7. Repeat step 6;
8. Observe that there's a newline between the two tasks, breaking the continuity of the checklist, which makes some plugins stop working

**Expected behavior**
No newline between the two newly added tasks at end of that file.

**Screenshots**
![image](https://user-images.githubusercontent.com/1171143/126861000-a2ff1fb1-1917-45a7-8542-d278e1dbfc64.png)

![image](https://user-images.githubusercontent.com/1171143/126861004-48b11419-0efc-4c22-9615-8eacf5172460.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Version [e.g. 22] 0.3.14

**Smartphone (please complete the following information):**

**Additional context**
The problem doesn't happen when there's no trailing newline in the file. But after the choice is used, a newline gets inserted.

**Comment by chhoumann** [comment]
Hey @ericaxu! Thank you very much for your report. Will you check if it is working as intended now? :)

**Comment by ericaxu** [comment]
@chhoumann Works as a charm now! As long as I remember to leave a newline after tasks I manually create.

But much much better! Really appreciate it.

**Comment by chhoumann** [comment]
Awesome! Thank you, @ericaxu!
