### ISSUE TITLE
[FEATURE REQUEST] add a ribbon icon

### ISSUE THREAD

**Issue by materemias** [chhoumann/quickadd#575]
**Is your feature request related to a problem? Please describe.**
On the android client it's not that easy to have a one tab solution to call up quick add, would be great if I could have that. I know there are plugins which can add custom command ribbon items, I'd prefer have it baked in

**Describe the solution you'd like**
A ribbon icon with quick add command

Thanks for considering

**Comment by aprather51** [comment]
+1

**Comment by chhoumann** [comment]
Added by @coryjthompson in #708 :)
