### ISSUE TITLE
[FEATURE REQUEST] Open Note after capture

### ISSUE THREAD

**Issue by chrisgrieser** [chhoumann/quickadd#58]
**Is your feature request related to a problem? Please describe.**
Not a big problem, but a convenience thing. For example, I'd like to add a card to a Kanban-Board *and then* also open the Kanban Baord. I figured out how to do the former, but I didn't find out how to do the later automatically afterwards.

**Describe the solution you'd like**
Add a checkbox with "Open Note after capturing to it". Basically the same option that you already have when quickadding a template.

**Additional context**
I apologize in advance for creating this issue if you can already somehow do it with a Macro. I just did not figure out how.

**Comment by chhoumann** [comment]
Hey! I've just added this in the latest update. Would you check if it is as expected? =D

**Comment by chrisgrieser** [comment]
works perfectly. Thanks a lot! 🤗
