### ISSUE TITLE
[BUG]  cannot run the zotero script - i get an error code

### ISSUE THREAD

**Issue by mini1416** [chhoumann/quickadd#589]
Hello,
when I run the zotero script through quickadd I get this error message: 
![image](https://github.com/chhoumann/quickadd/assets/148547737/8a9f54ec-b8d7-484f-be51-9f2bbbbeafc8)

Can anyone tell me what this error message means?

Thank you

**Comment by chhoumann** [comment]
Error 500 means Internal Server Error.

I just tested the script, and it seems to run for me, so I'm not sure the servers are having issues right now.
Did you set up the script with settings?

**Comment by mini1416** [comment]
Hi thank you for your reply,

when I click the javascript file : 
![image](https://github.com/chhoumann/quickadd/assets/148547737/885d361e-ec8d-4670-bc00-54e3d4b2c786)
This happens:
![image](https://github.com/chhoumann/quickadd/assets/148547737/d6adfc2d-fb6e-41b7-8998-0bf169fe21c2)

I don't know if this is relevant or not.

**Comment by mini1416** [comment]
> Error 500 means Internal Server Error.
> 
> I just tested the script, and it seems to run for me, so I'm not sure the servers are having issues right now. Did you set up the script with settings?

Turned out I typed my zotero ID wrong i was just stupid :/

**Comment by aparente** [comment]
I'm actually getting the same error - not sure why. I checked my username and tried creating a new key but no avail. I only have one paper in my Zotero as a first test...maybe that's why?
