### ISSUE TITLE
[BUG] Prepend adds ontop of front matter which breaks properties 

### ISSUE THREAD

**Issue by jamie9090** [chhoumann/quickadd#592]
Love this plugin!

Prepend adds ontop of front matter which breaks properties 

Is there a way to add below front matter instead?

**Comment by Aya89** [comment]
This issue is solved with this contribution #595 .

**Comment by chhoumann** [comment]
Thank you for reporting this. It was indeed fixed by @evanaze - I've just made a release with the bugfix :)
