### ISSUE TITLE
[Feature request] Add regsiter command feature like admonition plugin does?

### ISSUE THREAD

**Issue by Quorafind** [chhoumann/quickadd#6]
Here is a screenshot about what it did.

![image](https://user-images.githubusercontent.com/13215013/122254717-f528b480-ceff-11eb-9ed9-e08da3c41a99.png)

![image](https://user-images.githubusercontent.com/13215013/122254792-0d003880-cf00-11eb-85be-97774f5ce302.png)

And the code here might help you with it?:

https://github.com/valentine195/obsidian-admonition/blob/3d37aad23ba217dc12770f738ec1cdafa83fcfbd/src/settings.ts#L191

If it is hard to add this feature, you have done tons of goooood job! Thanks.

WHY I NEED THIS

I could quick run some command and don't need to wait.

**Comment by chhoumann** [comment]
Added =D
