### ISSUE TITLE
[FEATURE REQUEST] Add gpt-3.5-turbo-1106 model

### ISSUE THREAD

**Issue by Triquetra** [chhoumann/quickadd#601]
Thanks for the speedy update with gpt-4-1106-preview! I was wondering when we might be able to use that ...

It would also be really useful to have the gpt-3.5-turbo-1106 model available, as this is he upgraded gpt-3.5-turbo-16k model at a cheaper price.

**Comment by chhoumann** [comment]
Added in 1.6.0! Was too excited by GPT-4 Turbo that I missed this one.

**Comment by chhoumann** [comment]
https://github.com/chhoumann/quickadd/releases/tag/1.6.0
