### ISSUE TITLE
Please provide a capture path for...

### ISSUE THREAD

**Issue by davidszerman** [chhoumann/quickadd#62]
Hello,

I have created a capture action in order to test it ; very simple : 
- add in the active file
- nothing else (no format, no section to add to,...) and it does not work 👍 

It gives me the error Please provide a capture path for...

Thank you

**Comment by chhoumann** [comment]
Hey @davidszerman, thank you for your report! I cannot reproduce this error. Could you provide me with some additional screenshots and information about your setup?

Thank you :)

I tried to reproduce with this setup:
![image](https://user-images.githubusercontent.com/29108628/128482788-872d1c56-bef7-4879-92c9-a491d639c2a7.png)

Does it match your own?

**Comment by davidszerman** [comment]
Yes it does ; actually, it is really strange : I made a new simple
quickadd template. I had the same kind of error 'template' instead of
'capture' in the error message.

i restarted Obsidian and it works now... Maybe an issue with my
environment (it is a Citrix environment with some bugs)

Thanks

Le 2021-08-06T10:39:53.000+02:00, Christian Bager Bach Houmann
***@***.***> a écrit :

***@***.*** [https://github.com/davidszerman], thank you for

**Comment by chhoumann** [comment]
Thank you for your response! Now that is quite odd. I'm glad it works now, though. Sometime it just seems like a restart is all that's necessary.

**Comment by Ravenclawer** [comment]
I have encounter the same problem, when I use capture to active file open, it will produce error unless I open the "write to bottom of file" option
![image](https://user-images.githubusercontent.com/73892411/152742084-22665123-b218-4c95-b6ce-81d60ac4009e.png)
![image](https://user-images.githubusercontent.com/73892411/152742162-2ab08dbe-bf99-4c56-9531-65b66231b520.png)

**Comment by curtismchale** [comment]
I've had the same thing happen.

I was creating a template for a screencast. I got it working, documented it and then deleted it.

I went to create a new `capture` QuickAdd...thing, and did the exact same steps, including naming it the same thing. When I went to use it I was told I needed to define a path.

Simple quitting Obsidian and restarting it with no other changes made it work.

In my case, I wonder if there was some caching issue with the capture template name that was reading the setting from the old one so it didn't know where it should go.

**Comment by evelynwright** [comment]
Oh my goodness, thanks for this! New user of the the plugin, I was absolutely banging my head against the wall trying to figure out why I was getting the "Please provide a capture path" error. Isn't saying Capture to the active file specifying the path?

Quitting and restarting Obsidian made it work. Maybe add this to readme to spare future headbruises??

I am using it on MacOS, so I guess it's not an OS-specific thing?

Thanks for the plugin, I think it will change the game!!

**Comment by shangjin88** [comment]
> 我也发生过同样的事情。
> 
> 我正在为截屏视频创建一个模板。我让它工作，记录它，然后删除它。
> 
> 我去创建了一个新的快速添加...事物，并执行了完全相同的步骤，包括将其命名为相同的事物。当我使用它时，我被告知我需要定义一条路径。`capture`
> 
> 只需退出黑曜石并重新启动它，没有其他更改即可使其正常工作。
> 
> 在我的情况下，我想知道捕获模板名称是否存在一些缓存问题，该名称正在从旧模板中读取设置，因此它不知道它应该去哪里。

yes, i do

**Comment by chhoumann** [comment]
Just a quick update for everyone. The latest QA update should fix the issue where choices with commands wouldn't update. I think that has been what we've seen with this issue.
