### ISSUE TITLE
[BUG] checkboxPrompt duplicates values

### ISSUE THREAD

**Issue by thorlucas** [chhoumann/quickadd#63]
**Describe the bug**
When using`checkboxPrompt` with old values, the returned array has duplicate values.

**To Reproduce**
```javascript
const values = await checkboxPrompt(['a', 'b', 'c', 'd'], ['a', 'b']);
console.log(values);
```

If you turn OFF `a` and `b`, and turn ON `c`, you get the correct output: `['c']`.
However, if you leave `a` or `b` on, they are duplicated in the result: `["a", "b", "a", "b", "c"]`

**Comment by thorlucas** [comment]
Oh, it also for some reason tries to modify the "old values" array.

**Comment by chhoumann** [comment]
Hello @thorlucas, thank you for your report! Can you please test if the bug has been fixed in the latest update? 0.3.19 :)

**Comment by thorlucas** [comment]
> Hello @thorlucas, thank you for your report! Can you please test if the bug has been fixed in the latest update? 0.3.19 :)

Unfortunately there appears to be another bug now:

```javascript
const values = await checkboxPrompt(['a', 'b', 'c', 'd'], ['a']);

// Deselect A -> [] (good)
// Deselect A, Select B -> [] (bad)
// Select B -> ['b'] (bad)
```

I would be happy to take a look at this issue for you. Can you assign it to me?

**Comment by chhoumann** [comment]
That would be great, thank you!

**Comment by thorlucas** [comment]
Fairly simple fix, will close the issue once merged in

**Comment by chhoumann** [comment]
Thank you!
