### ISSUE TITLE
[BUG] Assistant Status 429

### ISSUE THREAD

**Issue by devinat1** [chhoumann/quickadd#666]
**Describe the bug**
I get a status 429 when attempting to use the OpenAI API.

**To Reproduce**
Trigger the default AI settings with OpenAI manual prompt (or any other prompt).

**Expected behavior**

**Screenshots**
![image](https://github.com/chhoumann/quickadd/assets/15788108/e70db241-3cb3-45ce-a338-94cbeaed9022)

**Desktop (please complete the following information):**
SYSTEM INFO:
	Obsidian version: v1.5.11
	Installer version: v1.4.16
	Operating system: Windows 10 Home 10.0.26085
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Base theme: dark
	Community theme: Minimal v7.5.3
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 58
	Plugins enabled: 20
		1: Templater v2.2.3
		2: Tab Switcher v1.4.0
		3: Google Photos v1.6.5
		4: Dataview v0.5.65
		5: Editor Syntax Highlight v0.1.3
		6: Minimal Theme Settings v7.3.1
		7: Commander v0.5.1
		8: Quick Switcher++ v4.0.0
		9: Canvas Mindmap v0.1.9
		10: Auto Link Title v1.5.3
		11: Admonition v10.2.0
		12: Simple CanvaSearch v0.1.0
		13: QuickAdd v1.8.1
		14: Zotero Integration v3.1.7
		15: Excalidraw v2.0.25
		16: Todoist Sync v1.12.0
		17: Linter v1.23.2
		18: Readwise Official v2.0.1
		19: Pandoc Plugin v0.4.1
		20: WakaTime v1.0.0

**Additional context**
I had not changed settings at all. The issue seemed to begin occurring when the change was made which allowed to change the settings of which assistant was available for use.

**Comment by chhoumann** [comment]
Hi @devinat1, thank you for the detailed issue! 

429 means Too Many Requests. Have you been using the assistant a lot? That could be an explanation in this case.

**Comment by devinat1** [comment]
@chhoumann 
> Hi @devinat1, thank you for the detailed issue!
> 
> 429 means Too Many Requests. Have you been using the assistant a lot? That could be an explanation in this case.

Nope not a lot. Just once a month or so.

**Comment by devinat1** [comment]
@chhoumann The issue was that I went over in the number of credits I had spent on my account.

**Comment by chhoumann** [comment]
Thank you for letting me know, @devinat1! Was scratching my head at this.
