### ISSUE TITLE
Folder path setting cannot be saved

### ISSUE THREAD

**Issue by tyf2018** [chhoumann/quickadd#7]
Folder path setting cannot be saved，as shown in the following screenshot

![C_2021 06 17_11 22 22](https://user-images.githubusercontent.com/56342788/122326121-5aab8e00-cf5e-11eb-8f48-f6a616f77067.jpg)

**Comment by chhoumann** [comment]
Hey! I've been trying to recreate this, but haven't been able to.

Could you walk me through the steps you take?

Is it the enabling of the setting that doesn't save? Or does it not, when you write a folder path and press enter, save that path?

**Comment by aviskase** [comment]
I also thought it was a bug, but apparently I wasn't using it correctly!

After you select the folder you need to type Enter and it will actually add a folder.

@chhoumann maybe a button "Add" next to the selection field will make it more clear?

**Comment by tyf2018** [comment]
As @aviskase says, an extra hit of the enter key is required to save correctly.Thanks aviskase for the answer.
There is another problem though, after adding a path, clicking the delete button does not work.
![C_2021 06 18_09 51 04](https://user-images.githubusercontent.com/56342788/122493694-b6d3e800-d01a-11eb-82cb-73ea82c77611.jpg)

**Comment by chhoumann** [comment]
You are absolutely right. I will add buttons to make this more clear. Thank you!

> As @aviskase says, an extra hit of the enter key is required to save correctly.Thanks aviskase for the answer.
> There is another problem though, after adding a path, clicking the delete button does not work.
> ![C_2021 06 18_09 51 04](https://user-images.githubusercontent.com/56342788/122493694-b6d3e800-d01a-11eb-82cb-73ea82c77611.jpg)

This should already have been fixed. Please update to the latest version :)
