### ISSUE TITLE
[BUG] AI Assistant throws 404 before making any network calls

### ISSUE THREAD

**Issue by rossoj85** [chhoumann/quickadd#734]
Hi, 

I am currently trying to set up AI assistant. I have watched your guide and have set up AI assistant accordingly. Once I select a prompt (template) it throws a 404 error immediately. I have tried with both Ollama and OpenAI. I investigated by opening the network tab in the console, and it appears that it is not even making a request before returning the error. I do not think the error is with Ollama, since I am successfully using it with other AI tools and it is probably an issue with my quicadd configuration. Any help would be appreciated. Thanks 

![image](https://github.com/user-attachments/assets/c4831568-47d0-4407-b7a9-1c29f86c8e34)

![image](https://github.com/user-attachments/assets/54879bd4-3c32-4433-8769-6341978d1c08)

![image](https://github.com/user-attachments/assets/1520a3e4-0e29-4b77-9553-dcf7b09b863e)

**Comment by alejandroarmas** [comment]
I'm encountering the same issue. 
<img width="351" alt="image" src="https://github.com/user-attachments/assets/c97d5f80-7e85-4f48-aab1-8ec30ffae66a">

**Comment by chhoumann** [comment]
Hi @rossoj85 and @alejandroarmas 

Your Ollama host should be `http://localhost:11434/v1`.

For example:
![image](https://github.com/user-attachments/assets/b79b4af1-4688-4702-a2cb-92693fed9418)
