### ISSUE TITLE
[BUG] Wrong multi-line input direction for RTL text

### ISSUE THREAD

**Issue by Hashemian01** [chhoumann/quickadd#739]
**Describe the bug**
In multi-line input, the RTL text does not have the correct direction. The single-line input is fine though.

**To Reproduce**
copy this sample RTL text as input 

```
لورم ایپسوم
```

Single-line input ✅

https://github.com/user-attachments/assets/cbbc41be-1061-4328-95a8-0fab8140f76b

Multi-line input ❌

https://github.com/user-attachments/assets/d74abfa5-0d67-4f85-a376-ae62c1ed7259

Obsidian Version = v1.6.7
Operating System: Windows 11

**Comment by chhoumann** [comment]
Thank you for opening this issue! Should be resolved as of the latest version - please let me know if not. Providing text I could test with is very much appreciated :)
