### ISSUE TITLE
failed to load plugin ''quickadd''

### ISSUE THREAD

**Issue by MCXopjesh** [chhoumann/quickadd#749]
### Discussed in https://github.com/chhoumann/quickadd/discussions/747

<div type='discussions-op-text'>

<sup>Originally posted by **rubyame** October 24, 2024</sup>
Hello I installed this plugin first time but I can't load it. My current version is v1.7.4, I need some help please</div>

**Comment by MCXopjesh** [comment]
Just to retell what i said on that thread:

Windows 10

Obsidian v1.7.4
Installer v1.6.7
Quickadd v1.11.1

All of which are up to date at the time of writing this on 11/01/2024

The error occurs any time I attempt to enable the plugin. If I try to use the toggle switch, the switch will not flip. If i use the enable button on the plugin page, the toggle switch will flip but it still will not work.

I attempted to install QuickAdd on a fresh vault and restarted my computer, but the error persists.

Looking into the code, I get this error message:

Plugin failure: quickadd DOMException: Failed to execute 'structuredClone' on 'Window': W=>b(d=>({...d,...W})) could not be cloned.
at i5 (plugin:quickadd:55:5868)
at async GI.onload (plugin:quickadd:73:7765)

That's the most I could find out

**Comment by chhoumann** [comment]
Hey, I'm sorry for taking so long about getting this fixed! It should hopefully be resolved now. I hope you enjoy QuickAdd, and please let me know if there are any further issues. All the best, Christian.

**Comment by chhoumann** [comment]
Please see https://github.com/chhoumann/quickadd/issues/728
