### ISSUE TITLE
[BUG] Script steps in macros don’t run on iOS

### ISSUE THREAD

**Issue by Dyldog** [chhoumann/quickadd#79]
**Describe the bug**

When running from iOS, if a macro choice has a script step in it, the macro stops running at the script step and doesn't run subsequent steps.

**To Reproduce**

1. Create a macro with a user script step and then a capture step
2. Run the macro from iOS
3. Observe that nothing happens (including insertion from capture step)
4. Remove the script step from the macro
5. Run the macro again
6. Observe that capture step text is inserted

**Expected behavior**

Macros with scripts should run on iOS

**Desktop (please complete the following information):**
 - OS: 

**Smartphone (please complete the following information):**
 - Device: iOS 
 - OS: iOS 14.7.1

**Additional context**

No errors or console log outputs

**Comment by frankreporting** [comment]
Similar experience. I have macros where the only step is a script and they don't run at all on mobile. I'm wondering if scripts simply don't work on mobile right now?

**Comment by dfjones** [comment]
I also just experienced this issue. It appears the scripts were synced to iOS, but they aren't able to execute.

**Comment by chhoumann** [comment]
Hey @Dyldog!
I've made a fix that, from my tests, make scripts work on mobile as they do on desktop. I'll push the fix in the next update.
