### ISSUE TITLE
plugin not fully functioning, any dependencies/known issues/etc?

### ISSUE THREAD

**Issue by lobosaid-g** [chhoumann/quickadd#85]
### Discussed in https://github.com/chhoumann/quickadd/discussions/83

<div type='discussions-op-text'>

<sup>Originally posted by **lobosaid-g** August 19, 2021</sup>
This is a really interesting plugin, however, for me, it only works with one combination, i.e., when I have 'Capture to active file' and 'Write to the bottom of the file' enabled. If I enable any other option, the capture doesn't work (I can input data but it just doesn't do anything). So, I was wondering, is there any requirement or something else that might be interfering with the plugin?

Thanks! </div>

**Comment by lobosaid-g** [comment]
So, I did some digging/investigation and the error I'm getting is: 
`QuickAdd: (LOG) TypeError: Cannot read property 'parse_template' of undefined`
Hence, there is some issue between this plugin and Templater, I just disable the Templater and this plugin is working fine, I will check further in order to make these two plugins work together...

**Comment by swehba** [comment]
This plugin has so much potential, but with 48 issues and counting development on it appears to have halted. Anyone know what the plans are for supporting this plugin, or would it be best if we just uninstalled it?

**Comment by lobosaid-g** [comment]
@chhoumann forgot to reply back on your latest comment... so, yes, this was due to an issue not using the updated version of templater
