### ISSUE TITLE
[BUG] Each restart of Obsidian will automatically run the macro command.

### ISSUE THREAD

**Issue by tyf2018** [chhoumann/quickadd#96]
**Describe the bug**
Each restart of Obsidian will automatically run the macro command.

**To Reproduce**
Restart Obsidian every time

**Expected behavior**
Do not run macro commands automatically

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [window 10]
 - Browser [chrome93.0.4577.63]
 - Version [Obsidian0.12.15]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by chhoumann** [comment]
Hey! Is the 'Run on plugin load' enabled for the macro?

![image](https://user-images.githubusercontent.com/29108628/131959730-78761f5f-9343-453d-953f-ad0575c9d801.png)

**Comment by tyf2018** [comment]
> 嘿！是否为宏启用了“在插件加载时运行”？
> 
> ![图片](https://user-images.githubusercontent.com/29108628/131959730-78761f5f-9343-453d-953f-ad0575c9d801.png)

This is indeed the case, I was too careless to see this setting item, thank you very much!
### In addition, the plugin is really great!
