### ISSUE TITLE
[FEATURE REQUEST] paste template to current file

### ISSUE THREAD

**Issue by johans3** [chhoumann/quickadd#98]
**Is your feature request related to a problem? Please describe.**

I'm puzzled why templates can't be added to (the end or beginning of) our current note. 
I like to elaborate notes, and generating new notes adds just to an endless pile of notes to review 

**Describe the solution you'd like**
Quickadd should paste templates to the current note as well :
1. At the beginning of the current note
2. At the end of the current note 
3. At the cursor position (if possible) 

**Additional context**
I'm using "hotkeys for templates" but would prefer quickadd instead

**Comment by chhoumann** [comment]
Hey! You can actually already do this with a capture. You can use the `{{TEMPLATE:...}}}` syntax to do it.

Check the format syntax in the documentation for more.

**Comment by johans3** [comment]
> Hey! You can actually already do this with a capture. You can use the `{{TEMPLATE:...}}}` syntax to do it.
> 
> Check the format syntax in the documentation for more.

After reading your message, it took some seconds to build my new template script... 😂

Your plugin description is pretty minimalist but functional, probably I skimmed too much
